/** Favourable / unfavourable activities per dasha lord, in English and Sinhala. */

import type { BiList } from '../i18n';

export const FAVORABLE: Record<string, BiList> = {
  Sun: {
    en: [
      'Starting leadership roles or applying for senior positions',
      'Government applications, licenses, and official matters',
      'Medical treatments and seeking diagnosis',
      'Purchasing gold, copper, or orange/red items',
      'Father-related ceremonies and family gatherings',
      'Public appearances, speeches, and recognition events',
    ],
    si: [
      'නායකත්ව තනතුරු භාර ගැනීම හෝ ජ්‍යෙෂ්ඨ තනතුරු සඳහා ඉල්ලුම් කිරීම',
      'රාජ්‍ය ඉල්ලුම්පත්, බලපත්‍ර හා නිල කටයුතු',
      'වෛද්‍ය ප්‍රතිකාර ගැනීම හා රෝග විනිශ්චය කරවා ගැනීම',
      'රන්, තඹ හෝ තැඹිලි හා රතු පැහැති දෑ මිලදී ගැනීම',
      'පියා ආශ්‍රිත උත්සව හා පවුලේ එකතුවීම්',
      'ප්‍රසිද්ධියේ පෙනී සිටීම, දේශන හා සම්මාන උත්සව',
    ],
  },
  Moon: {
    en: [
      'Starting new ventures during bright fortnight (Shukla Paksha)',
      'Real estate transactions and property matters',
      'Long-distance or near-water travel and pilgrimages',
      'Nurturing and charitable activities for women and children',
      'Creative and artistic pursuits requiring emotional depth',
      'Water-related activities and ocean or river rituals',
    ],
    si: [
      'පුර පක්ෂය තුළ නව ව්‍යාපෘති ආරම්භ කිරීම',
      'දේපළ ගනුදෙනු හා ඉඩම් කටයුතු',
      'දිගු දුර හෝ ජලාශ අසල ගමන් හා වන්දනා ගමන්',
      'කාන්තාවන් හා දරුවන් වෙනුවෙන් රැකබලා ගැනීමේ හා පුණ්‍ය කටයුතු',
      'හැඟීම්බර ගැඹුරක් අවශ්‍ය නිර්මාණශීලී හා කලාත්මක කටයුතු',
      'ජලය ආශ්‍රිත කටයුතු හා මුහුදු හෝ ගංගා පූජා',
    ],
  },
  Mars: {
    en: [
      'Property transactions and real estate investments',
      'Intense sports, physical activities, and martial arts',
      'Medically necessary or elective surgeries',
      'Mechanical work, engineering projects, and technical initiatives',
      'Sibling-related matters and family legal settlements',
      'Competitive examinations and performance challenges',
    ],
    si: [
      'දේපළ ගනුදෙනු හා ඉඩම් ආයෝජන',
      'තීව්‍ර ක්‍රීඩා, ශාරීරික ක්‍රියාකාරකම් හා සටන් කලා',
      'වෛද්‍යමය වශයෙන් අවශ්‍ය හෝ තෝරා ගත් සැත්කම්',
      'යාන්ත්‍රික වැඩ, ඉංජිනේරු ව්‍යාපෘති හා තාක්ෂණික මුල පිරීම්',
      'සහෝදර සහෝදරියන් ආශ්‍රිත කටයුතු හා පවුලේ නීතිමය බේරුම්',
      'තරඟකාරී විභාග හා දක්ෂතා අභියෝග',
    ],
  },
  Mercury: {
    en: [
      'Business venture launches and commercial agreements',
      'Educational pursuits, certifications, and skill upgrades',
      'Writing, publishing, blogging, and media projects',
      'Communication projects and networking events',
      'Short travels and local business trips',
      'Financial planning, budgeting, and investment research',
    ],
    si: [
      'ව්‍යාපාර ආරම්භ කිරීම හා වාණිජ ගිවිසුම්',
      'අධ්‍යාපන කටයුතු, සහතික ලබා ගැනීම හා කුසලතා දියුණු කිරීම',
      'ලේඛන, ප්‍රකාශන, බ්ලොග් හා මාධ්‍ය ව්‍යාපෘති',
      'සන්නිවේදන ව්‍යාපෘති හා සම්බන්ධතා ගොඩනඟන උත්සව',
      'කෙටි ගමන් හා දේශීය ව්‍යාපාරික ගමන්',
      'මූල්‍ය සැලසුම්, අයවැය සකස් කිරීම හා ආයෝජන පිළිබඳ අධ්‍යයනය',
    ],
  },
  Jupiter: {
    en: [
      'Marriage ceremonies and engagement announcements',
      'Religious activities, temple visits, and sacred rituals',
      'Higher education admissions and academic pursuits',
      'Legal filings and court-related activities',
      'Teaching, mentoring, and knowledge-sharing activities',
      'Charity donations and humanitarian service projects',
    ],
    si: [
      'විවාහ මංගල්‍ය හා පොරොන්දු උත්සව',
      'ආගමික කටයුතු, පන්සල් වන්දනා හා පූජා විධි',
      'උසස් අධ්‍යාපනයට ඇතුළත් වීම හා අධ්‍යයන කටයුතු',
      'නීතිමය ලේඛන ගොනු කිරීම හා උසාවි ආශ්‍රිත කටයුතු',
      'ඉගැන්වීම, මඟ පෙන්වීම හා දැනුම බෙදා දීමේ කටයුතු',
      'පුණ්‍ය දානමය කටයුතු හා මානුෂීය සේවා ව්‍යාපෘති',
    ],
  },
  Venus: {
    en: [
      'Marriage ceremonies and romantic commitments',
      'Artistic projects, music, dance, and creative pursuits',
      'Luxury purchases, jewelry, vehicles, and fine items',
      'Beauty treatments, self-care, and wellness activities',
      'Entertainment events and social celebrations',
      'Partnership agreements and collaborative business ventures',
    ],
    si: [
      'විවාහ මංගල්‍ය හා ප්‍රේම බැඳීම්',
      'කලාත්මක ව්‍යාපෘති, සංගීතය, නර්තනය හා නිර්මාණශීලී කටයුතු',
      'සුඛෝපභෝගී භාණ්ඩ, ස්වර්ණාභරණ, වාහන හා අගනා දෑ මිලදී ගැනීම',
      'රූපලාවණ්‍ය ප්‍රතිකාර, ස්වයං සත්කාරය හා සුවතා කටයුතු',
      'විනෝදාස්වාද උත්සව හා සමාජ සැමරුම්',
      'හවුල්කාරිත්ව ගිවිසුම් හා එක්ව කරන ව්‍යාපාර',
    ],
  },
  Saturn: {
    en: [
      'Long-term financial and life planning sessions',
      'Real estate investments (with patience for results)',
      'Service and volunteer activities for the underprivileged',
      'Discipline-intensive work requiring sustained effort',
      'Iron, steel, oil, gas, mining industry activities',
      'Agricultural investments and land development projects',
    ],
    si: [
      'දිගු කාලීන මූල්‍ය හා ජීවන සැලසුම් සකස් කිරීම',
      'දේපළ ආයෝජන (ප්‍රතිඵල සඳහා ඉවසීමෙන් සිටිය යුතුය)',
      'අඩු පහසුකම් ලත් අය වෙනුවෙන් සේවා හා ස්වේච්ඡා කටයුතු',
      'අඛණ්ඩ වෑයමක් අවශ්‍ය විනයගරුක වැඩකටයුතු',
      'යකඩ, වානේ, තෙල්, ගෑස් හා පතල් කර්මාන්ත කටයුතු',
      'කෘෂිකාර්මික ආයෝජන හා ඉඩම් සංවර්ධන ව්‍යාපෘති',
    ],
  },
  Rahu: {
    en: [
      'Technology ventures and digital business launches',
      'Foreign trade, export-import, and international business',
      'Research projects and investigative journalism',
      'Unconventional paths, startup ventures, and innovation',
      'Political activities and media campaigns',
      'Innovation projects and disruptive technology development',
    ],
    si: [
      'තාක්ෂණික ව්‍යාපෘති හා ඩිජිටල් ව්‍යාපාර ආරම්භ කිරීම',
      'විදේශ වෙළඳාම, අපනයන හා ආනයන හා ජාත්‍යන්තර ව්‍යාපාර',
      'පර්යේෂණ ව්‍යාපෘති හා විමර්ශන මාධ්‍යවේදය',
      'සම්ප්‍රදායික නොවන මාර්ග, ආරම්භක ව්‍යාපාර හා නවෝත්පාදන',
      'දේශපාලන කටයුතු හා මාධ්‍ය ව්‍යාපාර',
      'නවෝත්පාදන ව්‍යාපෘති හා පරිවර්තනීය තාක්ෂණ සංවර්ධනය',
    ],
  },
  Ketu: {
    en: [
      'Spiritual practices, meditation retreats, and yoga',
      'Research, investigation, and deep analytical studies',
      'Healing activities, alternative medicine, and energy work',
      'Consciously letting go of old, limiting patterns and relationships',
      'Occult studies, esoteric learning, and spiritual education',
      'Meditation retreats and silent spiritual immersion programs',
    ],
    si: [
      'අධ්‍යාත්මික පිළිවෙත්, භාවනා වැඩසටහන් හා යෝග',
      'පර්යේෂණ, විමර්ශන හා ගැඹුරු විශ්ලේෂණ අධ්‍යයන',
      'සුවකිරීමේ කටයුතු, විකල්ප වෛද්‍ය ක්‍රම හා ශක්ති චිකිත්සාව',
      'පැරණි, සීමා කරන රටා හා සම්බන්ධතා දැනුවත්ව අත්හැරීම',
      'ගුප්ත විද්‍යා අධ්‍යයන හා අධ්‍යාත්මික අධ්‍යාපනය',
      'භාවනා නිවහන් හා නිහඬ අධ්‍යාත්මික වැඩසටහන්',
    ],
  },
};

export const UNFAVORABLE: Record<string, BiList> = {
  Sun: {
    en: [
      'Decisions driven purely by ego and pride',
      'Open conflicts with authority figures, government, or employers',
      'Prolonged overexposure to direct sunlight without protection',
      'Neglecting regular health checkups, especially heart and eyes',
      'Arrogant, dismissive, or domineering behavior with others',
      'Disrespecting, ignoring, or neglecting your father relationship',
    ],
    si: [
      'අහංකාරය හා උඩඟුකම මත පමණක් ගන්නා තීරණ',
      'බලධාරීන්, රජය හෝ සේවා යෝජකයන් සමඟ විවෘත ගැටුම්',
      'ආරක්ෂාවකින් තොරව දිගු වේලාවක් හිරු එළියේ රැඳී සිටීම',
      'නිතිපතා සෞඛ්‍ය පරීක්ෂාවන් — විශේෂයෙන් හෘදය හා ඇස් — නොසලකා හැරීම',
      'අන් අය සමඟ උඩඟු, නොසලකා හරින හෝ ආධිපත්‍යය දරන හැසිරීම',
      'පියා සමඟ ඇති සම්බන්ධය නොසලකා හැරීම හෝ අගෞරව කිරීම',
    ],
  },
  Moon: {
    en: [
      'Major irreversible decisions on new moon or dark nights',
      'Purely emotional, reactive, and ungrounded major decisions',
      'Neglecting mental health, emotional wellbeing, and self-care',
      'Chronic dehydration, poor water intake, and irregular eating',
      'Disrespecting, neglecting, or being dismissive of your mother',
      'Irregular, chaotic sleep patterns and chronic sleep deprivation',
    ],
    si: [
      'අමාවක දිනවල හෝ අඳුරු රාත්‍රීවල ආපසු හැරවිය නොහැකි ප්‍රධාන තීරණ ගැනීම',
      'හැඟීම් මත පමණක් හදිසියේ ගන්නා, යථාර්ථයෙන් තොර ප්‍රධාන තීරණ',
      'මානසික සෞඛ්‍යය, හැඟීම්බර සුවතාව හා ස්වයං සත්කාරය නොසලකා හැරීම',
      'ශරීරයේ ජලය අඩු වීම, ප්‍රමාණවත් ජලය නොගැනීම හා අක්‍රමවත් ආහාර වේල්',
      'මවට අගෞරව කිරීම, නොසලකා හැරීම හෝ ඇය නොතකා සිටීම',
      'අක්‍රමවත් නින්ද රටා හා නිදිවර්ජිතව සිටීම',
    ],
  },
  Mars: {
    en: [
      'Impulsive, reactive, and unplanned major decisions',
      'Highly risky, unresearched ventures without proper planning',
      'Unnecessary arguments, heated confrontations, and conflicts',
      'Dangerous sports or physical activities without proper safety',
      'Ignoring injuries, wounds, and physical health symptoms',
      'Destructive disputes with siblings or property co-owners',
    ],
    si: [
      'හදිසියේ, නොසිතා සැලසුමකින් තොරව ගන්නා ප්‍රධාන තීරණ',
      'නිසි සැලසුමකින් හා අධ්‍යයනයකින් තොර අධි අවදානම් ව්‍යාපෘති',
      'අනවශ්‍ය තර්ක, උණුසුම් ගැටුම් හා ආරවුල්',
      'නිසි ආරක්ෂාවකින් තොර අනතුරුදායක ක්‍රීඩා හෝ ශාරීරික ක්‍රියාකාරකම්',
      'තුවාල හා ශාරීරික රෝග ලක්ෂණ නොසලකා හැරීම',
      'සහෝදරයන් හෝ දේපළ හවුල්කරුවන් සමඟ විනාශකාරී ආරවුල්',
    ],
  },
  Mercury: {
    en: [
      'Signing contracts without fully reading and understanding them',
      'Deliberate miscommunication, deception, or manipulation of information',
      'Chronic overthinking, analysis paralysis, and mental overload',
      'Neglecting ongoing education, skill development, and learning',
      'Dishonest, deceptive, or misleading financial or commercial dealings',
      'Excessive, compulsive screen time and digital device addiction',
    ],
    si: [
      'සම්පූර්ණයෙන් කියවා තේරුම් නොගෙන ගිවිසුම්වලට අත්සන් කිරීම',
      'හිතාමතා වැරදි තොරතුරු දීම, වංචා කිරීම හෝ තොරතුරු විකෘති කිරීම',
      'අධික ලෙස සිතීම, තීරණ ගත නොහැකි වීම හා මානසික බර',
      'අඛණ්ඩ අධ්‍යාපනය, කුසලතා සංවර්ධනය හා ඉගෙනීම නොසලකා හැරීම',
      'අවංක නොවන, වංචනික හෝ නොමඟ යවන මූල්‍ය හෝ වාණිජ ගනුදෙනු',
      'අධික ලෙස තිරය ඉදිරියේ කාලය ගත කිරීම හා ඩිජිටල් උපකරණවලට ඇබ්බැහි වීම',
    ],
  },
  Jupiter: {
    en: [
      'Unethical professional practices and cutting moral corners',
      'Disrespecting, ignoring, or undermining teachers and gurus',
      'Excessive indulgence in food, drink, pleasure, or comfort',
      'Neglecting spiritual growth, practice, and inner development',
      'Arrogance about knowledge, wisdom, or intellectual attainment',
      'Reckless financial extravagance and excessive material spending',
    ],
    si: [
      'සදාචාර විරෝධී වෘත්තීය පිළිවෙත් හා සදාචාරය බිඳ දැමීම',
      'ගුරුවරුන්ට හා ආචාර්යවරුන්ට අගෞරව කිරීම හෝ ඔවුන් නොතකා හැරීම',
      'ආහාර, පාන, සුඛය හෝ පහසුව අධික ලෙස විඳීම',
      'අධ්‍යාත්මික වර්ධනය, පිළිවෙත් හා අභ්‍යන්තර දියුණුව නොසලකා හැරීම',
      'දැනුම, ඥානය හෝ බුද්ධිමය සාධනය ගැන උඩඟු වීම',
      'නොසැලකිලිමත් අධික වියදම් හා භෞතික දෑ සඳහා නාස්තිය',
    ],
  },
  Venus: {
    en: [
      'Serious overindulgence in sensory pleasures and excess',
      'Extramarital affairs, infidelity, and relationship dishonesty',
      'Excessive luxury spending beyond genuine financial capacity',
      'Neglecting, dismissing, or devaluing your primary partner',
      'Superficial, transactional, and materialistic relationships',
      'Vanity-driven and appearance-obsessed life choices and decisions',
    ],
    si: [
      'ඉන්ද්‍රිය සුඛය අධික ලෙස විඳීම හා නාස්තිය',
      'විවාහයෙන් පිටත සම්බන්ධතා, විශ්වාසය කඩ කිරීම හා අවංක නොවීම',
      'සැබෑ මූල්‍ය හැකියාව ඉක්මවා සුඛෝපභෝගී වියදම් කිරීම',
      'ඔබේ ප්‍රධාන සහකරු හෝ සහකාරිය නොසලකා හැරීම හෝ අවතක්සේරු කිරීම',
      'මතුපිටින් පවතින, ගනුදෙනුවක් වැනි හා භෞතිකවාදී සම්බන්ධතා',
      'මාන්නය හා පෙනුම ගැන පමණක් සිතා ගන්නා ජීවන තීරණ',
    ],
  },
  Saturn: {
    en: [
      'Actively avoiding legitimate responsibilities and obligations',
      'Disrespecting, ignoring, or mistreating workers and the poor',
      'Chronic impatience with process, people, and necessary delays',
      'Taking unethical shortcuts and compromising personal integrity',
      'Ignoring and dismissing chronic or slow-developing health issues',
      'Persistent laziness, procrastination, and passive resistance',
    ],
    si: [
      'නීත්‍යානුකූල වගකීම් හා යුතුකම් හිතාමතා මඟහැරීම',
      'සේවකයන්ට හා දුප්පතුන්ට අගෞරව කිරීම හෝ අයුතු ලෙස සැලකීම',
      'ක්‍රියාවලිය, මිනිසුන් හා අවශ්‍ය ප්‍රමාදයන් ගැන නොඉවසිලිමත් වීම',
      'සදාචාර විරෝධී කෙටි මං ගැනීම හා පෞද්ගලික අවංකභාවය බිඳ දැමීම',
      'නිදන්ගත හෝ සෙමින් වර්ධනය වන සෞඛ්‍ය ගැටලු නොසලකා හැරීම',
      'දිගින් දිගටම අලසකම, කල් දැමීම හා නිහඬ විරෝධය',
    ],
  },
  Rahu: {
    en: [
      'Get-rich-quick schemes, speculative gambling, and financial fraud',
      'Substance abuse, intoxicants, and compulsive addictive behaviors',
      'Deliberate deception, manipulation, and misleading of others',
      'Consistently ignoring ethical standards and moral principles',
      'Obsessive, addictive, and compulsive behavioral patterns',
      'Reckless, ungrounded ambition far exceeding current capacity',
    ],
    si: [
      'ඉක්මනින් පොහොසත් වීමේ ක්‍රම, සමපේක්ෂණ සූදුව හා මූල්‍ය වංචා',
      'මත්ද්‍රව්‍ය භාවිතය හා ඇබ්බැහි වූ හැසිරීම්',
      'හිතාමතා වංචා කිරීම, අන් අය හසුරුවීම හා නොමඟ යැවීම',
      'සදාචාර ප්‍රමිතීන් හා ධාර්මික මූලධර්ම දිගින් දිගටම නොසලකා හැරීම',
      'ඇලී ගැලී යන, ඇබ්බැහි වූ හැසිරීම් රටා',
      'වර්තමාන හැකියාව බෙහෙවින් ඉක්මවා යන, යථාර්ථයෙන් තොර අභිලාෂ',
    ],
  },
  Ketu: {
    en: [
      'Excessive material attachment when detachment is the clear lesson',
      'Actively ignoring your genuine spiritual calling and deeper purpose',
      'Strong resistance to necessary, inevitable, and growth-producing change',
      'Desperately holding onto people, roles, and situations from the past',
      'Harmful social isolation, withdrawal, and rejection of community support',
      'Consistently ignoring deep intuition, inner knowing, and spiritual guidance',
    ],
    si: [
      'අත්හැරීම පැහැදිලි පාඩම වන විට භෞතික දෑට අධික ලෙස ඇලුම් කිරීම',
      'ඔබේ සැබෑ අධ්‍යාත්මික කැඳවීම හා ගැඹුරු අරමුණ නොසලකා හැරීම',
      'අවශ්‍ය, නොවැළැක්විය හැකි හා වර්ධනය ගෙන දෙන වෙනස්කම්වලට දැඩි විරෝධය',
      'අතීතයේ මිනිසුන්, භූමිකා හා තත්ත්වයන් තදින් අල්ලා ගෙන සිටීම',
      'හානිකර සමාජ හුදෙකලාව හා ප්‍රජාවගේ සහය ප්‍රතික්ෂේප කිරීම',
      'ගැඹුරු ඉව, අභ්‍යන්තර දැනීම හා අධ්‍යාත්මික මඟපෙන්වීම දිගින් දිගටම නොසලකා හැරීම',
    ],
  },
};
