/**
 * Bilingual house-analysis prose: "lord of house X in house Y" readings,
 * planet-combination yogas, and the sentence frames — English and Sinhala.
 *
 * The 12×12 lord-in-house grid keeps `en`/`si` side by side per cell.
 */

import type { Bi, Lang } from '../i18n';

export const HOUSE_LORD_IN_HOUSE: Record<number, Record<number, Bi>> = {
  1: {
    1: { en: 'Lord of self in 1st — strong vitality, self-reliance, and a clearly defined personality. Health is generally robust.', si: 'ලග්නාධිපති පළමුවේ — ප්‍රබල ජීවශක්තිය, ස්වයංපෝෂිතභාවය හා පැහැදිලි පෞරුෂයක්. සෞඛ්‍යය සාමාන්‍යයෙන් ශක්තිමත්ය.' },
    2: { en: 'Lord of self in 2nd — wealth and family central to identity. Income through personal effort; speech is a key asset.', si: 'ලග්නාධිපති දෙවනවේ — ධනය හා පවුල අනන්‍යතාවට කේන්ද්‍රීයයි. පෞද්ගලික වෑයමෙන් ආදායම; වචනය ප්‍රධාන වත්කමකි.' },
    3: { en: 'Lord of self in 3rd — courageous, communicative, and self-driven. Writing, media, or siblings play a defining role.', si: 'ලග්නාධිපති තෙවනවේ — ධෛර්ය සම්පන්න, සන්නිවේදනශීලී හා ස්වයං පෙළඹවුම් සහිත. ලේඛන, මාධ්‍ය හෝ සහෝදරයන් තීරණාත්මක කාර්යභාරයක් ඉටු කරයි.' },
    4: { en: 'Lord of self in 4th — deep roots in home and homeland. Mother is central; emotional peace is essential to function.', si: 'ලග්නාධිපති සිව්වනවේ — නිවස හා උපන් රට තුළ ගැඹුරු මුල්. මව කේන්ද්‍රීයයි; ක්‍රියාකාරී වීමට හැඟීම්බර සාමය අත්‍යවශ්‍යය.' },
    5: { en: 'Lord of self in 5th — creative intelligence defines the personality. Children and romantic life are life themes.', si: 'ලග්නාධිපති පස්වනවේ — නිර්මාණශීලී බුද්ධිය පෞරුෂය නිර්වචනය කරයි. දරුවන් හා ප්‍රේම ජීවිතය ජීවිත තේමා වේ.' },
    6: { en: 'Lord of self in 6th — life shaped by service, competition, and overcoming obstacles. Health requires active management.', si: 'ලග්නාධිපති හයවනවේ — ජීවිතය සේවය, තරඟය හා බාධක ජය ගැනීම මගින් හැඩ ගැසේ. සෞඛ්‍යයට ක්‍රියාශීලී කළමනාකරණයක් අවශ්‍යය.' },
    7: { en: 'Lord of self in 7th — partnerships are the mirror of self. Identity is strongly shaped by spouse or close partners.', si: 'ලග්නාධිපති හත්වනවේ — හවුල්කාරිත්ව ආත්මයේ කැඩපතයි. අනන්‍යතාව කලත්‍රයා හෝ සමීප සහකරුවන් විසින් ප්‍රබලව හැඩ ගැසේ.' },
    8: { en: 'Lord of self in 8th — life involves deep transformation, research, and hidden knowledge. Longevity-focused energy.', si: 'ලග්නාධිපති අටවනවේ — ජීවිතය ගැඹුරු පරිවර්තනය, පර්යේෂණ හා සැඟවුණු දැනුම ඇතුළත් වේ. ආයුෂ කේන්ද්‍ර කරගත් ශක්තිය.' },
    9: { en: 'Lord of self in 9th — fortunate, philosophical, and spiritually oriented. Father is a strong positive influence.', si: 'ලග්නාධිපති නවවනවේ — වාසනාවන්ත, දාර්ශනික හා අධ්‍යාත්මික නැඹුරුවක් සහිත. පියා ප්‍රබල හිතකර බලපෑමකි.' },
    10: { en: 'Lord of self in 10th — career and public status are central life themes. Strong professional drive.', si: 'ලග්නාධිපති දහවනවේ — වෘත්තිය හා මහජන තත්ත්වය කේන්ද්‍රීය ජීවිත තේමා වේ. ප්‍රබල වෘත්තීය ආශාව.' },
    11: { en: 'Lord of self in 11th — gains, social networks, and desires drive the personality. Income through personal initiative.', si: 'ලග්නාධිපති එකොළොස්වනවේ — ලාභ, සමාජ ජාල හා ආශාවන් පෞරුෂය මෙහෙයවයි. පෞද්ගලික මුල පිරීමෙන් ආදායම.' },
    12: { en: 'Lord of self in 12th — introspective, spiritual, or foreign-oriented. Hidden talents emerge through solitude.', si: 'ලග්නාධිපති දොළොස්වනවේ — අභ්‍යන්තර මෙනෙහි කරන, අධ්‍යාත්මික හෝ විදේශ නැඹුරු. හුදෙකලාව හරහා සැඟවුණු දක්ෂතා මතු වේ.' },
  },
  2: {
    1: { en: 'Wealth lord in 1st — financial prosperity tied to personal effort and health. Self-made wealth accumulation.', si: 'ධනාධිපති පළමුවේ — මූල්‍ය සමෘද්ධිය පෞද්ගලික වෑයම හා සෞඛ්‍යය සමඟ බැඳී ඇත. තමන්ම උපයන ධන රැස්කිරීම.' },
    2: { en: 'Wealth lord in own house — strong financial stability, good family, and accumulation over lifetime.', si: 'ධනාධිපති ස්වකීය භාවයේ — ප්‍රබල මූල්‍ය ස්ථාවරත්වය, හොඳ පවුලක් හා ජීවිත කාලය පුරා රැස්කිරීම.' },
    3: { en: 'Wealth lord in 3rd — income through communication, writing, or siblings. Multiple smaller income streams.', si: 'ධනාධිපති තෙවනවේ — සන්නිවේදනය, ලේඛන හෝ සහෝදරයන් හරහා ආදායම. කුඩා ආදායම් මාර්ග කිහිපයක්.' },
    4: { en: "Wealth lord in 4th — wealth through property, vehicles, and mother's support. Real estate is favorable.", si: 'ධනාධිපති සිව්වනවේ — දේපළ, වාහන හා මවගේ සහය හරහා ධනය. දේපළ වෙළඳාම හිතකරය.' },
    5: { en: 'Wealth lord in 5th — wealth through creativity, speculation, or children. Investments in education pay off.', si: 'ධනාධිපති පස්වනවේ — නිර්මාණශීලීත්වය, සමපේක්ෂණය හෝ දරුවන් හරහා ධනය. අධ්‍යාපනයේ ආයෝජන ප්‍රතිඵල දෙයි.' },
    6: { en: 'Wealth lord in 6th — financial challenges through debt or competition; income from service fields.', si: 'ධනාධිපති හයවනවේ — ණය හෝ තරඟය හරහා මූල්‍ය අභියෝග; සේවා ක්ෂේත්‍රවලින් ආදායම.' },
    7: { en: 'Wealth lord in 7th — financial gains through partnerships and business. Spouse contributes to wealth.', si: 'ධනාධිපති හත්වනවේ — හවුල්කාරිත්ව හා ව්‍යාපාර හරහා මූල්‍ය ලාභ. කලත්‍රයා ධනයට දායක වේ.' },
    8: { en: 'Wealth lord in 8th — wealth from hidden sources, inheritance, or joint finances. Sudden gains and losses.', si: 'ධනාධිපති අටවනවේ — සැඟවුණු මූලාශ්‍ර, උරුමය හෝ හවුල් මුදල් හරහා ධනය. හදිසි ලාභ හා පාඩු.' },
    9: { en: 'Wealth lord in 9th — very auspicious for wealth; fortune and luck amplify financial gains consistently.', si: 'ධනාධිපති නවවනවේ — ධනයට ඉතා සුබදායකයි; වාසනාව හා භාග්‍යය මූල්‍ය ලාභ නිරන්තරයෙන් වර්ධනය කරයි.' },
    10: { en: 'Wealth lord in 10th — income directly tied to career success. Professional status builds financial security.', si: 'ධනාධිපති දහවනවේ — ආදායම වෘත්තීය සාර්ථකත්වය සමඟ කෙලින්ම බැඳී ඇත. වෘත්තීය තත්ත්වය මූල්‍ය සුරක්ෂිතභාවය ගොඩනඟයි.' },
    11: { en: 'Wealth lord in 11th — excellent for gains; income multiplies through social networks and long-term effort.', si: 'ධනාධිපති එකොළොස්වනවේ — ලාභවලට විශිෂ්ටයි; සමාජ ජාල හා දිගු කාලීන වෑයම හරහා ආදායම ගුණ වේ.' },
    12: { en: 'Wealth lord in 12th — expenses exceed income; wealth goes to foreign lands, spiritual causes, or hospitals.', si: 'ධනාධිපති දොළොස්වනවේ — වියදම් ආදායම ඉක්මවයි; ධනය විදේශ රටවලට, අධ්‍යාත්මික කටයුතුවලට හෝ රෝහල්වලට යයි.' },
  },
  3: {
    1: { en: 'Courage lord in 1st — bold, self-assertive personality. Personal drive and communication are natural strengths.', si: 'තෙවන භාවාධිපති පළමුවේ — නිර්භීත, ස්ථිර පෞරුෂයක්. පෞද්ගලික ආශාව හා සන්නිවේදනය ස්වභාවික ශක්තීන් වේ.' },
    2: { en: 'Courage lord in 2nd — siblings contribute to wealth. Income through communication-based family businesses.', si: 'තෙවන භාවාධිපති දෙවනවේ — සහෝදරයන් ධනයට දායක වේ. සන්නිවේදනය පදනම් කරගත් පවුල් ව්‍යාපාර හරහා ආදායම.' },
    3: { en: 'Courage lord in own house — excellent for communication, writing, skills, and sibling relationships.', si: 'තෙවන භාවාධිපති ස්වකීය භාවයේ — සන්නිවේදනය, ලේඛන, කුසලතා හා සහෝදර සම්බන්ධතාවලට විශිෂ්ටයි.' },
    4: { en: 'Courage lord in 4th — connection between home and communication. Mother and siblings closely linked.', si: 'තෙවන භාවාධිපති සිව්වනවේ — නිවස හා සන්නිවේදනය අතර සම්බන්ධය. මව හා සහෝදරයන් සමීපව බැඳී ඇත.' },
    5: { en: 'Courage lord in 5th — creative writing and artistic skills shine. Short journeys lead to romance or creativity.', si: 'තෙවන භාවාධිපති පස්වනවේ — නිර්මාණශීලී ලේඛන හා කලාත්මක කුසලතා බබළයි. කෙටි ගමන් ප්‍රේමයට හෝ නිර්මාණශීලීත්වයට මඟ පාදයි.' },
    6: { en: 'Courage lord in 6th — competitive and courageous in service. Victory over enemies through communication.', si: 'තෙවන භාවාධිපති හයවනවේ — සේවයේදී තරඟකාරී හා ධෛර්ය සම්පන්න. සන්නිවේදනය හරහා සතුරන් මත ජයග්‍රහණය.' },
    7: { en: 'Courage lord in 7th — siblings or communication connected to marriage. Business partnerships in media.', si: 'තෙවන භාවාධිපති හත්වනවේ — සහෝදරයන් හෝ සන්නිවේදනය විවාහයට සම්බන්ධයි. මාධ්‍ය ක්ෂේත්‍රයේ ව්‍යාපාර හවුල්කාරිත්ව.' },
    8: { en: 'Courage lord in 8th — research, occult writing, and investigative journalism. Short journeys can be risky.', si: 'තෙවන භාවාධිපති අටවනවේ — පර්යේෂණ, ගුප්ත ලේඛන හා විමර්ශන මාධ්‍යවේදය. කෙටි ගමන් අවදානම් විය හැක.' },
    9: { en: 'Courage lord in 9th — philosophical writing and long-distance communication thrive. Sibling may be a guide.', si: 'තෙවන භාවාධිපති නවවනවේ — දාර්ශනික ලේඛන හා දිගු දුර සන්නිවේදනය සමෘද්ධිමත් වේ. සහෝදරයෙක් මඟපෙන්වන්නෙකු විය හැක.' },
    10: { en: 'Courage lord in 10th — career in communication, media, or skilled trades. Professional recognition for skills.', si: 'තෙවන භාවාධිපති දහවනවේ — සන්නිවේදන, මාධ්‍ය හෝ දක්ෂ ශිල්ප වෘත්තිය. කුසලතා සඳහා වෘත්තීය පිළිගැනීම.' },
    11: { en: 'Courage lord in 11th — gains through communication, siblings, and skilled work. Active social networking.', si: 'තෙවන භාවාධිපති එකොළොස්වනවේ — සන්නිවේදනය, සහෝදරයන් හා දක්ෂ කාර්ය හරහා ලාභ. ක්‍රියාශීලී සමාජ සම්බන්ධතා.' },
    12: { en: 'Courage lord in 12th — writing in solitude; foreign communication work. Spiritual journeys and retreats.', si: 'තෙවන භාවාධිපති දොළොස්වනවේ — හුදෙකලාවේ ලේඛන; විදේශ සන්නිවේදන කටයුතු. අධ්‍යාත්මික ගමන් හා නිවහන්.' },
  },
  4: {
    1: { en: 'Home lord in 1st — strong connection to homeland and mother. Identity rooted in heritage and property.', si: 'සිව්වන භාවාධිපති පළමුවේ — උපන් රට හා මව සමඟ ප්‍රබල සම්බන්ධයක්. අනන්‍යතාව උරුමය හා දේපළ තුළ මුල් බැස ඇත.' },
    2: { en: 'Home lord in 2nd — family wealth from property and ancestral resources. Beautiful home environment.', si: 'සිව්වන භාවාධිපති දෙවනවේ — දේපළ හා පාරම්පරික සම්පත් වලින් පවුල් ධනය. සුන්දර ගෘහ පරිසරයක්.' },
    3: { en: 'Home lord in 3rd — short journeys to the homeland; communication with mother and siblings is frequent.', si: 'සිව්වන භාවාධිපති තෙවනවේ — උපන් රටට කෙටි ගමන්; මව හා සහෝදරයන් සමඟ නිතර සන්නිවේදනය.' },
    4: { en: 'Home lord in own house — very auspicious; beautiful home, excellent mother relationship, and peaceful domestic life.', si: 'සිව්වන භාවාධිපති ස්වකීය භාවයේ — ඉතා සුබදායකයි; සුන්දර නිවසක්, විශිෂ්ට මව සම්බන්ධයක් හා සාමකාමී ගෘහ ජීවිතයක්.' },
    5: { en: 'Home lord in 5th — creativity born from home environment. Children bring domestic happiness.', si: 'සිව්වන භාවාධිපති පස්වනවේ — ගෘහ පරිසරයෙන් උපදින නිර්මාණශීලීත්වය. දරුවන් ගෘහ සතුට ගෙන එයි.' },
    6: { en: 'Home lord in 6th — property disputes or challenges with mother possible. Home maintenance needs attention.', si: 'සිව්වන භාවාධිපති හයවනවේ — දේපළ ආරවුල් හෝ මව සමඟ අභියෝග ඇති විය හැක. නිවස නඩත්තුවට අවධානය අවශ්‍යය.' },
    7: { en: 'Home lord in 7th — spouse connected to home and real estate. Business in property or domestic goods.', si: 'සිව්වන භාවාධිපති හත්වනවේ — කලත්‍රයා නිවස හා දේපළ සමඟ බැඳී ඇත. දේපළ හෝ ගෘහ භාණ්ඩ ව්‍යාපාර.' },
    8: { en: 'Home lord in 8th — ancestral property has hidden complications. Transformative home changes across life.', si: 'සිව්වන භාවාධිපති අටවනවේ — පාරම්පරික දේපළවල සැඟවුණු සංකීර්ණතා ඇත. ජීවිතය පුරා පරිවර්තනීය නිවස වෙනස්කම්.' },
    9: { en: 'Home lord in 9th — very auspicious; fortunate property gains and a wise, positive mother.', si: 'සිව්වන භාවාධිපති නවවනවේ — ඉතා සුබදායකයි; වාසනාවන්ත දේපළ ලාභ හා ඥානවන්ත, හිතකර මවක්.' },
    10: { en: 'Home lord in 10th — career in real estate, hospitality, or government. Home and career are linked.', si: 'සිව්වන භාවාධිපති දහවනවේ — දේපළ, ආගන්තුක සත්කාර හෝ රාජ්‍ය සේවා වෘත්තිය. නිවස හා වෘත්තිය බැඳී ඇත.' },
    11: { en: 'Home lord in 11th — gains from property and real estate. Home-based income sources thrive.', si: 'සිව්වන භාවාධිපති එකොළොස්වනවේ — දේපළ හා ඉඩම් වලින් ලාභ. නිවසින් කරන ආදායම් මාර්ග සමෘද්ධිමත් වේ.' },
    12: { en: 'Home lord in 12th — home may be in a foreign land. Property losses possible; spiritual home practice.', si: 'සිව්වන භාවාධිපති දොළොස්වනවේ — නිවස විදේශ රටක විය හැක. දේපළ පාඩු ඇති විය හැක; ගෘහයේ අධ්‍යාත්මික පිළිවෙත්.' },
  },
  5: {
    1: { en: "Intelligence lord in 1st — naturally creative and intelligent personality. Children are life's joy.", si: 'පස්වන භාවාධිපති පළමුවේ — ස්වභාවිකවම නිර්මාණශීලී හා බුද්ධිමත් පෞරුෂයක්. දරුවන් ජීවිතයේ සතුටයි.' },
    2: { en: 'Intelligence lord in 2nd — creative income and family wealth. Artistic or intellectual family tradition.', si: 'පස්වන භාවාධිපති දෙවනවේ — නිර්මාණශීලී ආදායම හා පවුල් ධනය. කලාත්මක හෝ බුද්ධිමය පවුල් සම්ප්‍රදායක්.' },
    3: { en: 'Intelligence lord in 3rd — creative writing and skills. Communication as artistic and intellectual expression.', si: 'පස්වන භාවාධිපති තෙවනවේ — නිර්මාණශීලී ලේඛන හා කුසලතා. කලාත්මක හා බුද්ධිමය ප්‍රකාශනයක් ලෙස සන්නිවේදනය.' },
    4: { en: "Intelligence lord in 4th — happiness through creative home. Children's education is prioritized.", si: 'පස්වන භාවාධිපති සිව්වනවේ — නිර්මාණශීලී නිවසක් හරහා සතුට. දරුවන්ගේ අධ්‍යාපනයට ප්‍රමුඛත්වය දෙයි.' },
    5: { en: 'Intelligence lord in own house — exceptional creativity, brilliant children, and strong spiritual merit.', si: 'පස්වන භාවාධිපති ස්වකීය භාවයේ — අසාමාන්‍ය නිර්මාණශීලීත්වය, දක්ෂ දරුවන් හා ප්‍රබල පින් බලය.' },
    6: { en: 'Intelligence lord in 6th — intelligence applied to service and problem-solving. Competition in creative fields.', si: 'පස්වන භාවාධිපති හයවනවේ — සේවය හා ගැටලු විසඳීමට යොදවන බුද්ධිය. නිර්මාණශීලී ක්ෂේත්‍රවල තරඟය.' },
    7: { en: 'Intelligence lord in 7th — creative partner; business in arts and creative education.', si: 'පස්වන භාවාධිපති හත්වනවේ — නිර්මාණශීලී සහකරු; කලා හා නිර්මාණශීලී අධ්‍යාපන ව්‍යාපාර.' },
    8: { en: 'Intelligence lord in 8th — research and occult intelligence. Deeply investigative and transformative thinking.', si: 'පස්වන භාවාධිපති අටවනවේ — පර්යේෂණ හා ගුප්ත බුද්ධිය. ගැඹුරින් විමර්ශනශීලී හා පරිවර්තනීය චින්තනය.' },
    9: { en: 'Intelligence lord in 9th — philosophical and dharmic creativity. Blessed children who are spiritually oriented.', si: 'පස්වන භාවාධිපති නවවනවේ — දාර්ශනික හා ධාර්මික නිර්මාණශීලීත්වය. අධ්‍යාත්මික නැඹුරුවක් ඇති පින්වත් දරුවන්.' },
    10: { en: 'Intelligence lord in 10th — career through creative intelligence. Professional recognition for mental abilities.', si: 'පස්වන භාවාධිපති දහවනවේ — නිර්මාණශීලී බුද්ධිය හරහා වෘත්තිය. මානසික හැකියාවන් සඳහා වෘත්තීය පිළිගැනීම.' },
    11: { en: "Intelligence lord in 11th — gains from creative ventures and children's success. Social circle includes artists.", si: 'පස්වන භාවාධිපති එකොළොස්වනවේ — නිර්මාණශීලී ව්‍යාපෘති හා දරුවන්ගේ සාර්ථකත්වයෙන් ලාභ. සමාජ කවයට කලාකරුවන් ඇතුළත් වේ.' },
    12: { en: 'Intelligence lord in 12th — creative and spiritual intelligence. Meditation and isolation fuel creativity.', si: 'පස්වන භාවාධිපති දොළොස්වනවේ — නිර්මාණශීලී හා අධ්‍යාත්මික බුද්ධිය. භාවනාව හා හුදෙකලාව නිර්මාණශීලීත්වයට ඉන්ධන සපයයි.' },
  },
  6: {
    1: { en: 'Obstacle lord in 1st — health challenges require active management. Strong competitive instinct.', si: 'හයවන භාවාධිපති පළමුවේ — සෞඛ්‍ය අභියෝගවලට ක්‍රියාශීලී කළමනාකරණයක් අවශ්‍යය. ප්‍රබල තරඟකාරී නැඹුරුව.' },
    2: { en: 'Obstacle lord in 2nd — financial debts and family disputes possible. Income through healthcare or legal work.', si: 'හයවන භාවාධිපති දෙවනවේ — මූල්‍ය ණය හා පවුල් ආරවුල් ඇති විය හැක. සෞඛ්‍ය සේවා හෝ නීති කටයුතු හරහා ආදායම.' },
    3: { en: 'Obstacle lord in 3rd — competitive communication and sibling rivalry. Courage through overcoming obstacles.', si: 'හයවන භාවාධිපති තෙවනවේ — තරඟකාරී සන්නිවේදනය හා සහෝදර තරඟය. බාධක ජය ගැනීම හරහා ධෛර්යය.' },
    4: { en: "Obstacle lord in 4th — domestic and property disputes. Mother's health needs attention.", si: 'හයවන භාවාධිපති සිව්වනවේ — ගෘහ හා දේපළ ආරවුල්. මවගේ සෞඛ්‍යයට අවධානය අවශ්‍යය.' },
    5: { en: 'Obstacle lord in 5th — challenges with children or speculative losses. Creativity overcoming difficulties.', si: 'හයවන භාවාධිපති පස්වනවේ — දරුවන් සමඟ අභියෝග හෝ සමපේක්ෂණ පාඩු. දුෂ්කරතා ජය ගන්නා නිර්මාණශීලීත්වය.' },
    6: { en: 'Obstacle lord in own house — strong in competition and service; enemies are defeated effectively.', si: 'හයවන භාවාධිපති ස්වකීය භාවයේ — තරඟයේ හා සේවයේ ප්‍රබලයි; සතුරන් ඵලදායී ලෙස පරාජය වේ.' },
    7: { en: 'Obstacle lord in 7th — marriage involves challenges or a partner with health issues. Legal business disputes.', si: 'හයවන භාවාධිපති හත්වනවේ — විවාහයේ අභියෝග හෝ සෞඛ්‍ය ගැටලු ඇති සහකරුවෙක්. නීතිමය ව්‍යාපාර ආරවුල්.' },
    8: { en: 'Obstacle lord in 8th — viparita raja yoga potential; obstacles transform into hidden strengths over time.', si: 'හයවන භාවාධිපති අටවනවේ — විපරීත රාජ යෝගයේ හැකියාව; බාධක කලින් කලට සැඟවුණු ශක්තීන් බවට හැරේ.' },
    9: { en: 'Obstacle lord in 9th — father faces challenges; fortune comes through overcoming adversity.', si: 'හයවන භාවාධිපති නවවනවේ — පියා අභියෝගවලට මුහුණ දෙයි; දුෂ්කරතා ජය ගැනීම හරහා වාසනාව එයි.' },
    10: { en: 'Obstacle lord in 10th — career in medicine, law, or competitive fields. Obstacles are professional catalysts.', si: 'හයවන භාවාධිපති දහවනවේ — වෛද්‍ය, නීති හෝ තරඟකාරී ක්ෂේත්‍රවල වෘත්තිය. බාධක වෘත්තීය උත්ප්‍රේරක වේ.' },
    11: { en: 'Obstacle lord in 11th — gains through service and competition. Income from healthcare or legal fields.', si: 'හයවන භාවාධිපති එකොළොස්වනවේ — සේවය හා තරඟය හරහා ලාභ. සෞඛ්‍ය සේවා හෝ නීති ක්ෂේත්‍රවලින් ආදායම.' },
    12: { en: 'Obstacle lord in 12th — viparita raja yoga; enemies self-destruct; hidden healing abilities emerge.', si: 'හයවන භාවාධිපති දොළොස්වනවේ — විපරීත රාජ යෝගය; සතුරන් තමන්ම විනාශ වේ; සැඟවුණු සුව කිරීමේ හැකියාවන් මතු වේ.' },
  },
  7: {
    1: { en: 'Partnership lord in 1st — identity strongly shaped by relationships. Public reputation matters greatly.', si: 'හත්වන භාවාධිපති පළමුවේ — අනන්‍යතාව සම්බන්ධතා මගින් ප්‍රබලව හැඩ ගැසේ. මහජන කීර්තිය බෙහෙවින් වැදගත් වේ.' },
    2: { en: 'Partnership lord in 2nd — spouse contributes to family wealth. Business partnerships in financial fields.', si: 'හත්වන භාවාධිපති දෙවනවේ — කලත්‍රයා පවුල් ධනයට දායක වේ. මූල්‍ය ක්ෂේත්‍රවල ව්‍යාපාර හවුල්කාරිත්ව.' },
    3: { en: 'Partnership lord in 3rd — communication with partner is central. Business partnerships in media or trade.', si: 'හත්වන භාවාධිපති තෙවනවේ — සහකරු සමඟ සන්නිවේදනය කේන්ද්‍රීයයි. මාධ්‍ය හෝ වෙළඳ ව්‍යාපාර හවුල්කාරිත්ව.' },
    4: { en: 'Partnership lord in 4th — spouse connected to home or real estate. Happy domestic married life.', si: 'හත්වන භාවාධිපති සිව්වනවේ — කලත්‍රයා නිවස හෝ දේපළ සමඟ බැඳී ඇත. සතුටුදායක ගෘහ විවාහ ජීවිතයක්.' },
    5: { en: 'Partnership lord in 5th — romantic and creative partnerships. Children come through happy marriage.', si: 'හත්වන භාවාධිපති පස්වනවේ — ප්‍රේමනීය හා නිර්මාණශීලී හවුල්කාරිත්ව. සතුටුදායක විවාහයක් හරහා දරුවන් ලැබේ.' },
    6: { en: 'Partnership lord in 6th — marriage requires extra effort and adjustment. Partner may have health issues.', si: 'හත්වන භාවාධිපති හයවනවේ — විවාහයට අමතර වෑයම හා ගැලපීම් අවශ්‍යය. සහකරුට සෞඛ්‍ය ගැටලු තිබිය හැක.' },
    7: { en: 'Partnership lord in own house — very favorable for marriage and partnerships. Supportive, well-matched spouse.', si: 'හත්වන භාවාධිපති ස්වකීය භාවයේ — විවාහයට හා හවුල්කාරිත්වවලට ඉතා හිතකරයි. සහායක, හොඳින් ගැළපෙන කලත්‍රයෙක්.' },
    8: { en: 'Partnership lord in 8th — marriage involves transformation and deep karmic connection.', si: 'හත්වන භාවාධිපති අටවනවේ — විවාහයේ පරිවර්තනය හා ගැඹුරු කර්ම සම්බන්ධයක් ඇතුළත් වේ.' },
    9: { en: 'Partnership lord in 9th — very auspicious; spouse from good family, fortunate partnership, foreign connections.', si: 'හත්වන භාවාධිපති නවවනවේ — ඉතා සුබදායකයි; හොඳ පවුලකින් කලත්‍රයෙක්, වාසනාවන්ත හවුල්කාරිත්වයක් හා විදේශ සම්බන්ධතා.' },
    10: { en: 'Partnership lord in 10th — career benefits from partnerships. Spouse supports professional ambitions.', si: 'හත්වන භාවාධිපති දහවනවේ — වෘත්තියට හවුල්කාරිත්වවලින් ප්‍රයෝජන. කලත්‍රයා වෘත්තීය අභිලාෂවලට සහය දෙයි.' },
    11: { en: 'Partnership lord in 11th — gains through partnerships and spouse. Business partnerships are financially rewarding.', si: 'හත්වන භාවාධිපති එකොළොස්වනවේ — හවුල්කාරිත්ව හා කලත්‍රයා හරහා ලාභ. ව්‍යාපාර හවුල්කාරිත්ව මූල්‍යමය වශයෙන් ප්‍රතිලාභදායීය.' },
    12: { en: 'Partnership lord in 12th — foreign spouse or partner; marriage involves sacrifice and spiritual depth.', si: 'හත්වන භාවාධිපති දොළොස්වනවේ — විදේශීය කලත්‍රයෙක් හෝ සහකරුවෙක්; විවාහයේ කැපකිරීම හා අධ්‍යාත්මික ගැඹුරක් ඇතුළත් වේ.' },
  },
  8: {
    1: { en: 'Transformation lord in 1st — life involves recurring cycles of transformation. Longevity and resilience are strong.', si: 'අටවන භාවාධිපති පළමුවේ — ජීවිතයේ පරිවර්තනයේ පුනරාවර්තන චක්‍ර ඇතුළත් වේ. ආයුෂ හා ප්‍රතිසන්ධානශීලීත්වය ප්‍රබලයි.' },
    2: { en: 'Transformation lord in 2nd — inheritance and hidden wealth are possible. Financial ups and downs through life.', si: 'අටවන භාවාධිපති දෙවනවේ — උරුමය හා සැඟවුණු ධනය ලැබිය හැක. ජීවිතය පුරා මූල්‍ය නැගීම් වැටීම්.' },
    3: { en: 'Transformation lord in 3rd — research writing and occult communication. Siblings connected to transformation.', si: 'අටවන භාවාධිපති තෙවනවේ — පර්යේෂණ ලේඛන හා ගුප්ත සන්නිවේදනය. සහෝදරයන් පරිවර්තනයට සම්බන්ධයි.' },
    4: { en: 'Transformation lord in 4th — home undergoes repeated transformation. Ancestral property has hidden history.', si: 'අටවන භාවාධිපති සිව්වනවේ — නිවස නැවත නැවත පරිවර්තනයට ලක් වේ. පාරම්පරික දේපළවල සැඟවුණු ඉතිහාසයක් ඇත.' },
    5: { en: 'Transformation lord in 5th — speculative and research intelligence. Hidden creative gifts and occult interests.', si: 'අටවන භාවාධිපති පස්වනවේ — සමපේක්ෂණ හා පර්යේෂණ බුද්ධිය. සැඟවුණු නිර්මාණශීලී දක්ෂතා හා ගුප්ත උනන්දුව.' },
    6: { en: 'Transformation lord in 6th — viparita raja yoga; hidden enemies self-destruct; strong karmic protection.', si: 'අටවන භාවාධිපති හයවනවේ — විපරීත රාජ යෝගය; සැඟවුණු සතුරන් තමන්ම විනාශ වේ; ප්‍රබල කර්ම ආරක්ෂාවක්.' },
    7: { en: 'Transformation lord in 7th — partner connected to occult or research. Marriage involves deep transformation.', si: 'අටවන භාවාධිපති හත්වනවේ — සහකරු ගුප්ත විද්‍යාව හෝ පර්යේෂණ සමඟ බැඳී ඇත. විවාහයේ ගැඹුරු පරිවර්තනයක් ඇතුළත් වේ.' },
    8: { en: 'Transformation lord in own house — powerful for longevity, occult knowledge, and hidden wealth.', si: 'අටවන භාවාධිපති ස්වකීය භාවයේ — ආයුෂ, ගුප්ත දැනුම හා සැඟවුණු ධනයට ප්‍රබලයි.' },
    9: { en: 'Transformation lord in 9th — philosophical transformation; fortune through research or hidden knowledge.', si: 'අටවන භාවාධිපති නවවනවේ — දාර්ශනික පරිවර්තනය; පර්යේෂණ හෝ සැඟවුණු දැනුම හරහා වාසනාව.' },
    10: { en: 'Transformation lord in 10th — career in research, medicine, insurance, or occult fields.', si: 'අටවන භාවාධිපති දහවනවේ — පර්යේෂණ, වෛද්‍ය, රක්ෂණ හෝ ගුප්ත ක්ෂේත්‍රවල වෘත්තිය.' },
    11: { en: 'Transformation lord in 11th — gains through research, joint finances, and transformation-related fields.', si: 'අටවන භාවාධිපති එකොළොස්වනවේ — පර්යේෂණ, හවුල් මුදල් හා පරිවර්තනය ආශ්‍රිත ක්ෂේත්‍ර හරහා ලාභ.' },
    12: { en: 'Transformation lord in 12th — viparita raja yoga; hidden strengths emerge; profound spiritual transformation.', si: 'අටවන භාවාධිපති දොළොස්වනවේ — විපරීත රාජ යෝගය; සැඟවුණු ශක්තීන් මතු වේ; ගැඹුරු අධ්‍යාත්මික පරිවර්තනයක්.' },
  },
  9: {
    1: { en: 'Fortune lord in 1st — naturally lucky and fortunate personality. Father is a positive life force.', si: 'නවවන භාවාධිපති පළමුවේ — ස්වභාවිකවම වාසනාවන්ත පෞරුෂයක්. පියා හිතකර ජීවන බලයකි.' },
    2: { en: 'Fortune lord in 2nd — family wealth and fortune aligned. Speech carries philosophical authority.', si: 'නවවන භාවාධිපති දෙවනවේ — පවුල් ධනය හා වාසනාව ගැළපී ඇත. වචනය දාර්ශනික බලයක් දරයි.' },
    3: { en: 'Fortune lord in 3rd — fortune through writing and communication. Siblings may be philosophical guides.', si: 'නවවන භාවාධිපති තෙවනවේ — ලේඛන හා සන්නිවේදනය හරහා වාසනාව. සහෝදරයන් දාර්ශනික මඟපෙන්වන්නන් විය හැක.' },
    4: { en: 'Fortune lord in 4th — fortunate home and mother. Property luck is strong; homeland brings blessings.', si: 'නවවන භාවාධිපති සිව්වනවේ — වාසනාවන්ත නිවසක් හා මවක්. දේපළ වාසනාව ප්‍රබලයි; උපන් රට ආශිර්වාද ගෙන එයි.' },
    5: { en: 'Fortune lord in 5th — excellent; creative fortune and blessed children. Spiritual merit from past lives rewards.', si: 'නවවන භාවාධිපති පස්වනවේ — විශිෂ්ටයි; නිර්මාණශීලී වාසනාව හා පින්වත් දරුවන්. පෙර භවවල පින් බලය ප්‍රතිඵල දෙයි.' },
    6: { en: 'Fortune lord in 6th — fortune through service and overcoming obstacles. Father faces challenges.', si: 'නවවන භාවාධිපති හයවනවේ — සේවය හා බාධක ජය ගැනීම හරහා වාසනාව. පියා අභියෝගවලට මුහුණ දෙයි.' },
    7: { en: 'Fortune lord in 7th — fortunate partnerships and marriage. Business luck through collaborations.', si: 'නවවන භාවාධිපති හත්වනවේ — වාසනාවන්ත හවුල්කාරිත්ව හා විවාහය. එක්ව කරන කටයුතු හරහා ව්‍යාපාර වාසනාව.' },
    8: { en: 'Fortune lord in 8th — fortune hidden in research and transformation. Sudden fortunate inheritances.', si: 'නවවන භාවාධිපති අටවනවේ — පර්යේෂණ හා පරිවර්තනය තුළ සැඟවුණු වාසනාව. හදිසි වාසනාවන්ත උරුම.' },
    9: { en: 'Fortune lord in own house — most auspicious; maximum luck, strong dharma, and philosophical mastery.', si: 'නවවන භාවාධිපති ස්වකීය භාවයේ — වඩාත්ම සුබදායකයි; උපරිම වාසනාව, ප්‍රබල ධර්මය හා දාර්ශනික ප්‍රවීණත්වය.' },
    10: { en: 'Fortune lord in 10th — career success brings fortune. Professional achievements align with life purpose.', si: 'නවවන භාවාධිපති දහවනවේ — වෘත්තීය සාර්ථකත්වය වාසනාව ගෙන එයි. වෘත්තීය ජයග්‍රහණ ජීවිත අරමුණ සමඟ ගැළපේ.' },
    11: { en: 'Fortune lord in 11th — exceptional gains; desires are fulfilled; social luck and fortune combined.', si: 'නවවන භාවාධිපති එකොළොස්වනවේ — අසාමාන්‍ය ලාභ; ආශාවන් ඉටු වේ; සමාජ වාසනාව හා භාග්‍යය එක් වේ.' },
    12: { en: 'Fortune lord in 12th — fortune in foreign lands or spiritual pursuit. Moksha-oriented life path.', si: 'නවවන භාවාධිපති දොළොස්වනවේ — විදේශ රටවල හෝ අධ්‍යාත්මික සෙවීමේ වාසනාව. මෝක්ෂය කේන්ද්‍ර කරගත් ජීවන මාර්ගයක්.' },
  },
  10: {
    1: { en: 'Career lord in 1st — career is a central life identity. Professional drive is the core personality trait.', si: 'දහවන භාවාධිපති පළමුවේ — වෘත්තිය කේන්ද්‍රීය ජීවිත අනන්‍යතාවයකි. වෘත්තීය ආශාව මූලික පෞරුෂ ලක්ෂණයයි.' },
    2: { en: 'Career lord in 2nd — career in family business or finance. Professional income directly builds family wealth.', si: 'දහවන භාවාධිපති දෙවනවේ — පවුල් ව්‍යාපාර හෝ මූල්‍ය වෘත්තිය. වෘත්තීය ආදායම කෙලින්ම පවුල් ධනය ගොඩනඟයි.' },
    3: { en: 'Career lord in 3rd — career in communication, media, or skilled trades. Siblings influence professional path.', si: 'දහවන භාවාධිපති තෙවනවේ — සන්නිවේදන, මාධ්‍ය හෝ දක්ෂ ශිල්ප වෘත්තිය. සහෝදරයන් වෘත්තීය මාර්ගයට බලපායි.' },
    4: { en: 'Career lord in 4th — career in real estate, hospitality, or homeland-based work. Work from home is possible.', si: 'දහවන භාවාධිපති සිව්වනවේ — දේපළ, ආගන්තුක සත්කාර හෝ උපන් රට පදනම් කරගත් වෘත්තිය. නිවසින් වැඩ කිරීම හැකියි.' },
    5: { en: 'Career lord in 5th — creative career. Work in arts, education, and entertainment brings recognition.', si: 'දහවන භාවාධිපති පස්වනවේ — නිර්මාණශීලී වෘත්තිය. කලා, අධ්‍යාපන හා විනෝදාස්වාද කටයුතු පිළිගැනීම ගෙන එයි.' },
    6: { en: 'Career lord in 6th — career in service, medicine, law, or competitive fields. Professional challenges sharpen skills.', si: 'දහවන භාවාධිපති හයවනවේ — සේවා, වෛද්‍ය, නීති හෝ තරඟකාරී ක්ෂේත්‍රවල වෘත්තිය. වෘත්තීය අභියෝග කුසලතා තියුණු කරයි.' },
    7: { en: 'Career lord in 7th — career through partnerships and public dealings. Business partnerships define professional life.', si: 'දහවන භාවාධිපති හත්වනවේ — හවුල්කාරිත්ව හා මහජන ගනුදෙනු හරහා වෘත්තිය. ව්‍යාපාර හවුල්කාරිත්ව වෘත්තීය ජීවිතය නිර්වචනය කරයි.' },
    8: { en: 'Career lord in 8th — career in research, medicine, insurance, or occult fields. Hidden professional talents.', si: 'දහවන භාවාධිපති අටවනවේ — පර්යේෂණ, වෛද්‍ය, රක්ෂණ හෝ ගුප්ත ක්ෂේත්‍රවල වෘත්තිය. සැඟවුණු වෘත්තීය දක්ෂතා.' },
    9: { en: 'Career lord in 9th — dharmic career aligned with philosophy and higher learning. Teaching or law is indicated.', si: 'දහවන භාවාධිපති නවවනවේ — දර්ශනය හා උසස් අධ්‍යාපනය සමඟ ගැළපෙන ධාර්මික වෘත්තිය. ඉගැන්වීම හෝ නීතිය පෙන්නුම් කරයි.' },
    10: { en: 'Career lord in own house — very powerful for career; exceptional professional success and public recognition.', si: 'දහවන භාවාධිපති ස්වකීය භාවයේ — වෘත්තියට ඉතා ප්‍රබලයි; අසාමාන්‍ය වෘත්තීය සාර්ථකත්වය හා මහජන පිළිගැනීම.' },
    11: { en: 'Career lord in 11th — career directly generates income gains. Professional social networks are financially rewarding.', si: 'දහවන භාවාධිපති එකොළොස්වනවේ — වෘත්තිය කෙලින්ම ආදායම් ලාභ ජනනය කරයි. වෘත්තීය සමාජ ජාල මූල්‍යමය වශයෙන් ප්‍රතිලාභදායීය.' },
    12: { en: 'Career lord in 12th — career in foreign lands, spirituality, or behind-the-scenes work.', si: 'දහවන භාවාධිපති දොළොස්වනවේ — විදේශ රටවල, අධ්‍යාත්මිකත්වයේ හෝ තිර පිටුපස කරන වෘත්තිය.' },
  },
  11: {
    1: { en: 'Gains lord in 1st — gains come through personal initiative. Self-made success and income growth.', si: 'එකොළොස්වන භාවාධිපති පළමුවේ — ලාභ පෞද්ගලික මුල පිරීම හරහා එයි. තමන්ම ගොඩනඟන සාර්ථකත්වය හා ආදායම් වර්ධනය.' },
    2: { en: 'Gains lord in 2nd — excellent for accumulated wealth. Family and personal financial goals align perfectly.', si: 'එකොළොස්වන භාවාධිපති දෙවනවේ — රැස් කරන ලද ධනයට විශිෂ්ටයි. පවුල් හා පෞද්ගලික මූල්‍ය ඉලක්ක පරිපූර්ණව ගැළපේ.' },
    3: { en: 'Gains lord in 3rd — gains through communication, siblings, and skilled work. Active networking generates income.', si: 'එකොළොස්වන භාවාධිපති තෙවනවේ — සන්නිවේදනය, සහෝදරයන් හා දක්ෂ කාර්ය හරහා ලාභ. ක්‍රියාශීලී සම්බන්ධතා ආදායම ජනනය කරයි.' },
    4: { en: 'Gains lord in 4th — gains through property, mother, and homeland. Real estate is a consistent income source.', si: 'එකොළොස්වන භාවාධිපති සිව්වනවේ — දේපළ, මව හා උපන් රට හරහා ලාභ. දේපළ ස්ථාවර ආදායම් මාර්ගයකි.' },
    5: { en: 'Gains lord in 5th — gains from creativity, children, and speculation. Creative ventures bring financial rewards.', si: 'එකොළොස්වන භාවාධිපති පස්වනවේ — නිර්මාණශීලීත්වය, දරුවන් හා සමපේක්ෂණයෙන් ලාභ. නිර්මාණශීලී ව්‍යාපෘති මූල්‍ය ප්‍රතිලාභ ගෙන එයි.' },
    6: { en: 'Gains lord in 6th — gains through service and competition. Income from healthcare or legal work is steady.', si: 'එකොළොස්වන භාවාධිපති හයවනවේ — සේවය හා තරඟය හරහා ලාභ. සෞඛ්‍ය සේවා හෝ නීති කටයුතුවලින් ආදායම ස්ථාවරයි.' },
    7: { en: 'Gains lord in 7th — gains through partnerships and business. Spouse contributes significantly to income goals.', si: 'එකොළොස්වන භාවාධිපති හත්වනවේ — හවුල්කාරිත්ව හා ව්‍යාපාර හරහා ලාභ. කලත්‍රයා ආදායම් ඉලක්කවලට සැලකිය යුතු දායකත්වයක් දෙයි.' },
    8: { en: 'Gains lord in 8th — sudden and unexpected gains from research, joint finances, or inheritance.', si: 'එකොළොස්වන භාවාධිපති අටවනවේ — පර්යේෂණ, හවුල් මුදල් හෝ උරුමයෙන් හදිසි හා අනපේක්ෂිත ලාභ.' },
    9: { en: 'Gains lord in 9th — very auspicious; fortune multiplies gains. Father or guru supports financial goals.', si: 'එකොළොස්වන භාවාධිපති නවවනවේ — ඉතා සුබදායකයි; වාසනාව ලාභ ගුණ කරයි. පියා හෝ ගුරුවරයා මූල්‍ය ඉලක්කවලට සහය දෙයි.' },
    10: { en: 'Gains lord in 10th — career is the primary source of gains. Professional success directly generates income.', si: 'එකොළොස්වන භාවාධිපති දහවනවේ — වෘත්තිය ලාභවල ප්‍රධාන මූලාශ්‍රයයි. වෘත්තීය සාර්ථකත්වය කෙලින්ම ආදායම ජනනය කරයි.' },
    11: { en: 'Gains lord in own house — most powerful for fulfilling desires and achieving consistent financial gains.', si: 'එකොළොස්වන භාවාධිපති ස්වකීය භාවයේ — ආශාවන් ඉටු කිරීමට හා ස්ථාවර මූල්‍ය ලාභ ලැබීමට වඩාත්ම ප්‍රබලයි.' },
    12: { en: 'Gains lord in 12th — gains go to foreign lands or spiritual causes. Expenses match income growth.', si: 'එකොළොස්වන භාවාධිපති දොළොස්වනවේ — ලාභ විදේශ රටවලට හෝ අධ්‍යාත්මික කටයුතුවලට යයි. වියදම් ආදායම් වර්ධනයට සමානය.' },
  },
  12: {
    1: { en: 'Liberation lord in 1st — introspective and spiritually oriented personality. Foreign travel shapes identity.', si: 'දොළොස්වන භාවාධිපති පළමුවේ — අභ්‍යන්තර මෙනෙහි කරන හා අධ්‍යාත්මික නැඹුරු පෞරුෂයක්. විදේශ ගමන් අනන්‍යතාව හැඩ ගස්වයි.' },
    2: { en: 'Liberation lord in 2nd — expenses from family and wealth resources. Foreign income supplements losses.', si: 'දොළොස්වන භාවාධිපති දෙවනවේ — පවුල හා ධන සම්පත් වලින් වියදම්. විදේශ ආදායම පාඩු පිරිමසයි.' },
    3: { en: 'Liberation lord in 3rd — journeys to isolated places. Writing and communication about spiritual topics.', si: 'දොළොස්වන භාවාධිපති තෙවනවේ — හුදෙකලා ස්ථානවලට ගමන්. අධ්‍යාත්මික විෂයයන් පිළිබඳ ලේඛන හා සන්නිවේදනය.' },
    4: { en: 'Liberation lord in 4th — home in a foreign land. Property may be in an institution or foreign territory.', si: 'දොළොස්වන භාවාධිපති සිව්වනවේ — විදේශ රටක නිවසක්. දේපළ ආයතනයක හෝ විදේශ භූමියක විය හැක.' },
    5: { en: 'Liberation lord in 5th — creative and spiritual intelligence. Children may be spiritually oriented.', si: 'දොළොස්වන භාවාධිපති පස්වනවේ — නිර්මාණශීලී හා අධ්‍යාත්මික බුද්ධිය. දරුවන් අධ්‍යාත්මික නැඹුරුවක් ඇති විය හැක.' },
    6: { en: 'Liberation lord in 6th — viparita raja yoga; hidden enemies lose their power; health improves through service.', si: 'දොළොස්වන භාවාධිපති හයවනවේ — විපරීත රාජ යෝගය; සැඟවුණු සතුරන්ට බලය අහිමි වේ; සේවය හරහා සෞඛ්‍යය වැඩිදියුණු වේ.' },
    7: { en: 'Liberation lord in 7th — foreign or spiritually oriented partner. Marriage involves sacrifice and transcendence.', si: 'දොළොස්වන භාවාධිපති හත්වනවේ — විදේශීය හෝ අධ්‍යාත්මික නැඹුරු සහකරුවෙක්. විවාහයේ කැපකිරීම හා ඉක්මවා යාම ඇතුළත් වේ.' },
    8: { en: 'Liberation lord in 8th — viparita raja yoga potential; deep spiritual transformation brings hidden strength.', si: 'දොළොස්වන භාවාධිපති අටවනවේ — විපරීත රාජ යෝගයේ හැකියාව; ගැඹුරු අධ්‍යාත්මික පරිවර්තනය සැඟවුණු ශක්තියක් ගෙන එයි.' },
    9: { en: 'Liberation lord in 9th — foreign philosophy and spiritual fortune. Father may live abroad or be spiritually inclined.', si: 'දොළොස්වන භාවාධිපති නවවනවේ — විදේශ දර්ශනය හා අධ්‍යාත්මික වාසනාව. පියා විදේශයක ජීවත් විය හැක හෝ අධ්‍යාත්මික නැඹුරුවක් ඇති විය හැක.' },
    10: { en: 'Liberation lord in 10th — career in foreign lands, spirituality, or behind-the-scenes work. Work in institutions.', si: 'දොළොස්වන භාවාධිපති දහවනවේ — විදේශ රටවල, අධ්‍යාත්මිකත්වයේ හෝ තිර පිටුපස කරන වෘත්තිය. ආයතනවල සේවය.' },
    11: { en: 'Liberation lord in 11th — gains through foreign sources and spiritual networks. Income from abroad.', si: 'දොළොස්වන භාවාධිපති එකොළොස්වනවේ — විදේශ මූලාශ්‍ර හා අධ්‍යාත්මික ජාල හරහා ලාභ. විදේශයෙන් ආදායම.' },
    12: { en: 'Liberation lord in own house — powerfully moksha-oriented; spiritual liberation is a central life theme.', si: 'දොළොස්වන භාවාධිපති ස්වකීය භාවයේ — ප්‍රබලව මෝක්ෂය කේන්ද්‍ර කරගත්; අධ්‍යාත්මික මිදීම කේන්ද්‍රීය ජීවිත තේමාවකි.' },
  },
};

// ─── Planet-combination yogas in a house ────────────────────────────────────

export const NOTABLE_COMBOS: Record<string, Bi> = {
  'Jupiter-Moon': { en: 'Gajakesari Yoga — Moon-Jupiter conjunction creates fame, wisdom, and public recognition.', si: 'ගජකේසරී යෝගය — චන්ද්‍ර-ගුරු එකතුව කීර්තිය, ඥානය හා මහජන පිළිගැනීම නිර්මාණය කරයි.' },
  'Jupiter-Sun': { en: 'Budhaditya-adjacent — Solar wisdom amplified; authority and knowledge combine powerfully.', si: 'බුධාදිත්‍යයට ආසන්න — සූර්ය ඥානය වර්ධනය වේ; බලය හා දැනුම ප්‍රබලව එක් වේ.' },
  'Mercury-Sun': { en: 'Budhaditya Yoga — intellect and authority united; excellent for communication and leadership.', si: 'බුධාදිත්‍ය යෝගය — බුද්ධිය හා බලය එක් වේ; සන්නිවේදනයට හා නායකත්වයට විශිෂ්ටයි.' },
  'Mars-Saturn': { en: 'Challenging conjunction — energy meets obstruction; discipline is essential to avoid frustration.', si: 'අභියෝගාත්මක එකතුව — ශක්තිය බාධාව හමු වේ; කලකිරීම වළක්වා ගැනීමට විනය අත්‍යවශ්‍යය.' },
  'Mars-Rahu': { en: 'High-energy volatile combination — ambition peaks but accidents and recklessness are risks.', si: 'ඉහළ ශක්තියක් සහිත අස්ථිර එකතුව — අභිලාෂය උච්ච වේ නමුත් අනතුරු හා නොසැලකිල්ල අවදානම් වේ.' },
  'Moon-Rahu': { en: 'Grahan influence — emotional turbulence and psychic intensity; mental health needs care.', si: 'ග්‍රහණ බලපෑම — හැඟීම්බර කැළඹීම හා අභ්‍යන්තර තීව්‍රතාව; මානසික සෞඛ්‍යයට සැලකිල්ල අවශ්‍යය.' },
  'Moon-Saturn': { en: 'Vish Yoga influence — emotional heaviness; depression risk; requires consistent spiritual practice.', si: 'විෂ යෝග බලපෑම — හැඟීම්බර බර; අවපීඩන අවදානම; නොකඩවා අධ්‍යාත්මික පිළිවෙත් අවශ්‍යය.' },
  'Jupiter-Saturn': { en: 'Dharma-Karma axis — philosophical discipline; slow but profound achievement in life.', si: 'ධර්ම-කර්ම අක්ෂය — දාර්ශනික විනය; ජීවිතයේ මන්දගාමී නමුත් ගැඹුරු ජයග්‍රහණයක්.' },
  'Mercury-Venus': { en: 'Artistic intelligence — creative, charming, and communicative; business in arts thrives.', si: 'කලාත්මක බුද්ධිය — නිර්මාණශීලී, ආකර්ෂණීය හා සන්නිවේදනශීලී; කලා ව්‍යාපාර සමෘද්ධිමත් වේ.' },
  'Sun-Saturn': { en: 'Ego meets karma — authority challenged; slow recognition but deeply earned status.', si: 'අහංකාරය කර්මය හමු වේ — බලය අභියෝගයට ලක් වේ; මන්දගාමී පිළිගැනීමක් නමුත් ගැඹුරින් උපයාගත් තත්ත්වයක්.' },
  'Venus-Rahu': { en: 'Intense desire for beauty and pleasure; unconventional relationships; charisma is magnetic.', si: 'සුන්දරත්වය හා සැපය සඳහා තීව්‍ර ආශාව; සම්ප්‍රදායට වෙනස් සම්බන්ධතා; ආකර්ෂණය චුම්බක සහගතයි.' },
  'Jupiter-Venus': { en: 'Lakshmi Yoga potential — wealth, beauty, and wisdom combine for material and spiritual prosperity.', si: 'ලක්ෂ්මී යෝගයේ හැකියාව — ධනය, සුන්දරත්වය හා ඥානය එක් වී භෞතික හා අධ්‍යාත්මික සමෘද්ධිය ගෙන දෙයි.' },
  'Ketu-Mars': { en: 'Past-life warrior energy — technical and surgical skills; accident risk intensified.', si: 'පෙර භවයේ රණශූර ශක්තිය — තාක්ෂණික හා ශල්‍ය කුසලතා; අනතුරු අවදානම තීව්‍ර වේ.' },
  'Moon-Mars': { en: 'Chandra-Mangala Yoga — emotional courage and protective instinct; real estate indicated.', si: 'චන්ද්‍ර-මංගල යෝගය — හැඟීම්බර ධෛර්යය හා ආරක්ෂාකාරී නැඹුරුව; දේපළ පෙන්නුම් කරයි.' },
};

/** Sentence frames used inside analyzeHouse. */
export const HOUSE_FRAMES = {
  lordFallback: (lord: string, houseNumber: number, lordHouse: number, lang: Lang): string =>
    lang === 'si'
      ? `${lord} (${houseNumber} වන භාවාධිපති) ${lordHouse} වන භාවයේ පිහිටා ඇත.`
      : `${lord} (lord of house ${houseNumber}) is placed in house ${lordHouse}.`,
  planetEffect: (planet: string, keywords: string, theme: string, isRetro: boolean, lang: Lang): string =>
    lang === 'si'
      ? `${planet} ${keywords} ${theme} වෙත ගෙන එයි${isRetro ? ' — නමුත් වක්‍ර ගමන නිසා අභ්‍යන්තරයට යොමු වේ' : ''}.`
      : `${planet} brings ${keywords} into ${theme}${isRetro ? ' — but turned inward due to retrograde motion' : ''}.`,
  stellium: (count: number, areaName: string, lang: Lang): string =>
    lang === 'si'
      ? `ග්‍රහයන් ${count} දෙනෙකුගේ එකතුවක් (ස්ටෙලියම්) — මෙම භාවයේ සංකේන්ද්‍රිත ශක්තිය ${areaName} හි සියලු තේමා වර්ධනය කරයි. ජීවිතය පුරාම මෙම භාවයේ සියලු කරුණු අවධානය හා තීව්‍රතාවෙන් යුක්ත වේ.`
      : `${count}-planet stellium — concentrated energy in this house amplifies all themes of ${areaName}. Focus and intensity characterize all matters of this house throughout life.`,
};
