/**
 * Planet-pair (mahadasha–antardasha) combination readings, in English and Sinhala.
 *
 * Key: `${mahadasha}-${antardasha}`, both Title-cased Vedic names.
 * `ratingMod` is language-independent and stays alongside the prose so the two
 * can never drift apart.
 */

import type { Bi } from '../i18n';

export interface PairEffect {
  theme: Bi;
  health: Bi;
  wealth: Bi;
  career: Bi;
  relationships: Bi;
  warning?: Bi;
  bonus?: Bi;
  /** −2 … +2 */
  ratingMod: number;
}

export const PAIR_EFFECTS: Record<string, PairEffect> = {
  // ─── Jupiter combinations (most benefic) ─────────────────────────────────
  'Jupiter-Jupiter': {
    theme: { en: 'Double Guru blessing — peak of wisdom, fortune and spiritual growth', si: 'ද්විගුණ ගුරු ආශිර්වාදය — ඥානය, වාසනාව හා අධ්‍යාත්මික වර්ධනයේ උච්චතම අවස්ථාව' },
    health: { en: 'Robust vitality; watch liver and weight', si: 'ජීවශක්තිය ප්‍රබලයි; අක්මාව හා ශරීර බර ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Excellent wealth accumulation, legal income, advisory fees', si: 'විශිෂ්ට ධන රැස්කිරීමක්, නීතිමය ආදායම් හා උපදේශන ගාස්තු' },
    career: { en: 'Teaching, consulting, and judicial roles peak', si: 'ඉගැන්වීම, උපදේශනය හා විනිශ්චය කටයුතු උච්චතම මට්ටමට පත් වේ' },
    relationships: { en: 'Marriage blessings, children flourish, elder respect', si: 'විවාහ ආශිර්වාද, දරුවන්ගේ දියුණුව හා වැඩිහිටියන්ගේ ගෞරවය' },
    bonus: { en: 'Strongest benefic combination; major life milestones likely', si: 'ප්‍රබලතම සුබ එකතුව; ජීවිතයේ ප්‍රධාන සන්ධිස්ථාන සිදු වීමට ඉඩ ඇත' },
    ratingMod: 2,
  },
  'Jupiter-Venus': {
    theme: { en: 'Guru-Shukra yoga — prosperity, beauty, and social recognition', si: 'ගුරු-ශුක්‍ර යෝගය — සමෘද්ධිය, සුන්දරත්වය හා සමාජ පිළිගැනීම' },
    health: { en: 'Generally good; kidney and throat need care', si: 'සාමාන්‍යයෙන් හොඳයි; වකුගඩු හා උගුර ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Strong financial gains, luxury, partnership income', si: 'ප්‍රබල මූල්‍ය ලාභ, සුඛෝපභෝගය හා හවුල්කාරිත්ව ආදායම්' },
    career: { en: 'Law, arts, hospitality, luxury brands excel', si: 'නීතිය, කලා, ආගන්තුක සත්කාරය හා සුඛෝපභෝගී වෙළඳ නාම සාර්ථක වේ' },
    relationships: { en: 'Romantic relationships blossom; marriage very favorable', si: 'ප්‍රේම සම්බන්ධතා පිපී යයි; විවාහය ඉතා හිතකරය' },
    bonus: { en: 'Wealth and beauty combine — ideal for creative professions', si: 'ධනය හා සුන්දරත්වය එක් වේ — නිර්මාණශීලී වෘත්තීන්ට කදිම කාලයකි' },
    ratingMod: 2,
  },
  'Jupiter-Mercury': {
    theme: { en: 'Guru-Budha yoga — intellectual and financial brilliance', si: 'ගුරු-බුධ යෝගය — බුද්ධිමය හා මූල්‍යමය දීප්තිය' },
    health: { en: 'Nervous system and liver need balance', si: 'ස්නායු පද්ධතිය හා අක්මාව සමතුලිතව තබා ගත යුතුය' },
    wealth: { en: 'Business acumen at peak; multiple income streams', si: 'ව්‍යාපාරික දක්ෂතාව උච්චතම මට්ටමේ; ආදායම් මාර්ග කිහිපයක්' },
    career: { en: 'Writing, teaching, financial advisory all favored', si: 'ලේඛන කලාව, ඉගැන්වීම හා මූල්‍ය උපදේශනය හිතකරය' },
    relationships: { en: 'Intellectual connections; meaningful conversations', si: 'බුද්ධිමය සම්බන්ධතා හා අර්ථවත් සංවාද' },
    bonus: { en: 'Excellent for education, publishing, and commerce', si: 'අධ්‍යාපනය, ප්‍රකාශන හා වාණිජ කටයුතුවලට විශිෂ්ටයි' },
    ratingMod: 2,
  },
  'Jupiter-Moon': {
    theme: { en: 'Gajakesari influence — emotional wisdom and public recognition', si: 'ගජකේසරී යෝගයේ බලපෑම — හැඟීම්බර ඥානය හා මහජන පිළිගැනීම' },
    health: { en: 'Good overall; mental clarity is high', si: 'සමස්තයක් ලෙස හොඳයි; මානසික පැහැදිලිකම ඉහළය' },
    wealth: { en: 'Public income, real estate, nurturing businesses', si: 'මහජනතාව ආශ්‍රිත ආදායම්, දේපළ හා සත්කාරක ව්‍යාපාර' },
    career: { en: 'Public-facing roles, consulting, and education thrive', si: 'මහජනතාව සමඟ ගනුදෙනු කරන තනතුරු, උපදේශනය හා අධ්‍යාපනය සමෘද්ධිමත් වේ' },
    relationships: { en: 'Deep family bonds; motherly relationships important', si: 'ගැඹුරු පවුල් බැඳීම්; මවගේ සම්බන්ධය වැදගත් වේ' },
    bonus: { en: 'Fame and public regard increase significantly', si: 'කීර්තිය හා මහජන ගෞරවය සැලකිය යුතු ලෙස වැඩි වේ' },
    ratingMod: 1,
  },
  'Jupiter-Sun': {
    theme: { en: 'Guru-Surya — divine authority, leadership and dharmic success', si: 'ගුරු-සූර්ය — දේව බලය, නායකත්වය හා ධාර්මික සාර්ථකත්වය' },
    health: { en: 'Heart and spine well-supported; vitality strong', si: 'හෘදය හා කොඳු ඇට පෙළ හොඳින් රැකෙයි; ජීවශක්තිය ප්‍රබලයි' },
    wealth: { en: 'Government contracts, authority-based income rises', si: 'රාජ්‍ය කොන්ත්‍රාත් හා නිලබලය ආශ්‍රිත ආදායම් වැඩි වේ' },
    career: { en: 'Leadership positions, government roles, academic recognition', si: 'නායකත්ව තනතුරු, රාජ්‍ය සේවා තනතුරු හා අධ්‍යයන පිළිගැනීම' },
    relationships: { en: 'Relationship with father and authority figures improves', si: 'පියා හා ඉහළ නිලධාරීන් සමඟ ඇති සම්බන්ධය වැඩිදියුණු වේ' },
    ratingMod: 1,
  },
  'Jupiter-Mars': {
    theme: { en: 'Guru-Mangal — righteous action and courageous expansion', si: 'ගුරු-කුජ — ධාර්මික ක්‍රියාව හා ධෛර්ය සම්පන්න ව්‍යාප්තිය' },
    health: { en: 'High energy; avoid excess heat and inflammation', si: 'ශක්තිය ඉහළය; අධික උණුසුම හා දැවිලි තත්ත්ව වළක්වා ගන්න' },
    wealth: { en: 'Property gains, technical businesses, bold investments pay off', si: 'දේපළ ලාභ, තාක්ෂණික ව්‍යාපාර හා නිර්භීත ආයෝජන ප්‍රතිඵල දෙයි' },
    career: { en: 'Law, military, technical leadership, entrepreneurship', si: 'නීතිය, හමුදා සේවය, තාක්ෂණික නායකත්වය හා ව්‍යවසායකත්වය' },
    relationships: { en: 'Siblings prosper; loyal friends emerge', si: 'සහෝදරයන් සමෘද්ධිමත් වේ; විශ්වාසවන්ත මිතුරන් හමු වේ' },
    ratingMod: 1,
  },
  'Jupiter-Saturn': {
    theme: { en: 'Guru-Shani — karma, wisdom through discipline and long-term growth', si: 'ගුරු-ශනි — කර්මය, විනය හරහා ලැබෙන ඥානය හා දිගු කාලීන වර්ධනය' },
    health: { en: 'Chronic conditions may arise; joints and liver', si: 'නිදන්ගත රෝග මතු විය හැක; සන්ධි හා අක්මාව ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Slow but solid wealth building; long-term investments', si: 'මන්දගාමී නමුත් ශක්තිමත් ධන ගොඩනැගීමක්; දිගු කාලීන ආයෝජන' },
    career: { en: 'Judiciary, administration, senior management roles', si: 'විනිශ්චය සේවය, පරිපාලනය හා ජ්‍යෙෂ්ඨ කළමනාකරණ තනතුරු' },
    relationships: { en: 'Serious commitments; karmic relationships surface', si: 'බැරෑරුම් කැපවීම්; කර්ම සම්බන්ධතා මතු වේ' },
    warning: { en: 'Progress is slow — patience is essential; avoid shortcuts', si: 'ප්‍රගතිය මන්දගාමීය — ඉවසීම අත්‍යවශ්‍යය; කෙටි මං වළක්වන්න' },
    ratingMod: 0,
  },
  'Jupiter-Rahu': {
    theme: { en: 'Guru-Chandal yoga — wisdom challenged by illusion', si: 'ගුරු-චණ්ඩාල යෝගය — මායාව නිසා ඥානය අභියෝගයට ලක් වේ' },
    health: { en: 'Mysterious health episodes; watch liver and toxins', si: 'හඳුනාගත නොහැකි රෝග තත්ත්ව; අක්මාව හා විෂ ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Foreign income possible; avoid speculative gains', si: 'විදේශ ආදායමක් ලැබිය හැක; සමපේක්ෂණ ලාභ වළක්වන්න' },
    career: { en: 'Unconventional teaching, foreign education, media roles', si: 'සම්ප්‍රදායික නොවන ඉගැන්වීම, විදේශ අධ්‍යාපනය හා මාධ්‍ය කටයුතු' },
    relationships: { en: 'Unusual relationships; foreign or non-traditional partners', si: 'අසාමාන්‍ය සම්බන්ධතා; විදේශීය හෝ සම්ප්‍රදායික නොවන සහකරුවන්' },
    warning: { en: 'Ethics must be guarded — illusion can cloud good judgment', si: 'සදාචාරය රැක ගත යුතුය — මායාව නිසා නිවැරදි විනිශ්චය මඟ හැරිය හැක' },
    ratingMod: -1,
  },
  'Jupiter-Ketu': {
    theme: { en: 'Guru-Ketu — spiritual detachment, past wisdom resurfaces', si: 'ගුරු-කේතු — අධ්‍යාත්මික වෙන්වීම; අතීත ඥානය යළි මතු වේ' },
    health: { en: 'Mysterious ailments; spiritual healing helps', si: 'හඳුනාගත නොහැකි ආබාධ; අධ්‍යාත්මික සුවකිරීම උපකාරී වේ' },
    wealth: { en: 'Material detachment; income from spiritual or research work', si: 'භෞතික දෑින් වෙන් වීම; අධ්‍යාත්මික හෝ පර්යේෂණ කටයුතුවලින් ආදායම' },
    career: { en: 'Research, philosophy, occult, spiritual teaching', si: 'පර්යේෂණ, දර්ශනය, ගුප්ත විද්‍යාව හා අධ්‍යාත්මික ඉගැන්වීම' },
    relationships: { en: 'Past-life connections surface; detachment from worldly bonds', si: 'පෙර භවවල බැඳීම් මතු වේ; ලෞකික බැඳීම්වලින් වෙන් වීමක්' },
    ratingMod: 0,
  },

  // ─── Venus combinations ──────────────────────────────────────────────────
  'Venus-Venus': {
    theme: { en: 'Double Shukra — peak of luxury, love and artistic excellence', si: 'ද්විගුණ ශුක්‍ර — සුඛෝපභෝගය, ආදරය හා කලාත්මක විශිෂ්ටත්වයේ උච්චතම අවස්ථාව' },
    health: { en: 'Reproductive and kidney health watch needed', si: 'ප්‍රජනන පද්ධතිය හා වකුගඩු සෞඛ්‍යය ගැන අවධානය අවශ්‍යය' },
    wealth: { en: 'Luxury businesses, arts, entertainment reach new heights', si: 'සුඛෝපභෝගී ව්‍යාපාර, කලා හා විනෝදාස්වාදය නව උසකට යයි' },
    career: { en: 'Fashion, beauty, hospitality, arts at peak performance', si: 'විලාසිතා, රූපලාවණ්‍ය, ආගන්තුක සත්කාරය හා කලා උච්චතම මට්ටමේ' },
    relationships: { en: 'Marriage and romance at pinnacle; social life flourishes', si: 'විවාහය හා ප්‍රේමය උච්චතම තත්ත්වයේ; සමාජ ජීවිතය සමෘද්ධිමත් වේ' },
    bonus: { en: 'Best period for marriage, artistic projects, and luxury', si: 'විවාහයට, කලාත්මක ව්‍යාපෘතිවලට හා සුඛෝපභෝගයට හොඳම කාලයයි' },
    ratingMod: 2,
  },
  'Venus-Jupiter': {
    theme: { en: 'Shukra-Guru — harmonious prosperity and spiritual love', si: 'ශුක්‍ර-ගුරු — සමගිකාමී සමෘද්ධිය හා අධ්‍යාත්මික ආදරය' },
    health: { en: 'Good vitality; weight and liver moderation needed', si: 'ජීවශක්තිය හොඳයි; ශරීර බර හා අක්මාව සම්බන්ධයෙන් සංයමය අවශ්‍යය' },
    wealth: { en: 'Major wealth accumulation through partnership and arts', si: 'හවුල්කාරිත්ව හා කලා හරහා විශාල ධන රැස්කිරීමක්' },
    career: { en: 'Arts, law, luxury, and finance all excel', si: 'කලා, නීතිය, සුඛෝපභෝගී අංශ හා මූල්‍ය සේවා සාර්ථක වේ' },
    relationships: { en: 'Marriage extremely favored; spouse brings wealth', si: 'විවාහයට ඉතා හිතකරය; කලත්‍රයා ධනය ගෙන එයි' },
    bonus: { en: 'One of the most auspicious combinations for marriage and wealth', si: 'විවාහයට හා ධනයට ඇති සුබදායකම එකතුවලින් එකකි' },
    ratingMod: 2,
  },
  'Venus-Mercury': {
    theme: { en: 'Shukra-Budha — creative intelligence and commercial success', si: 'ශුක්‍ර-බුධ — නිර්මාණශීලී බුද්ධිය හා වාණිජ සාර්ථකත්වය' },
    health: { en: 'Generally fine; skin and nervous system attention', si: 'සාමාන්‍යයෙන් හොඳයි; සම හා ස්නායු පද්ධතිය ගැන අවධානය යොමු කරන්න' },
    wealth: { en: 'Business, media, beauty, and technology income grows', si: 'ව්‍යාපාර, මාධ්‍ය, රූපලාවණ්‍ය හා තාක්ෂණ ආදායම් වර්ධනය වේ' },
    career: { en: 'Communication arts, digital media, fashion, and trade', si: 'සන්නිවේදන කලා, ඩිජිටල් මාධ්‍ය, විලාසිතා හා වෙළඳාම' },
    relationships: { en: 'Witty, charming social connections; romantic variety', si: 'චතුර, ආකර්ෂණීය සමාජ සම්බන්ධතා; ප්‍රේම කටයුතුවල විවිධත්වය' },
    ratingMod: 2,
  },
  'Venus-Moon': {
    theme: { en: 'Shukra-Chandra — emotional sensitivity and artistic expression', si: 'ශුක්‍ර-චන්ද්‍ර — හැඟීම්බර සංවේදිතාව හා කලාත්මක ප්‍රකාශනය' },
    health: { en: 'Water balance and reproductive health watch', si: 'ශරීරයේ ජල සමතුලිතතාව හා ප්‍රජනන සෞඛ්‍යය ගැන අවධානය' },
    wealth: { en: 'Public-facing businesses, hospitality, dairy, arts', si: 'මහජනතාව ආශ්‍රිත ව්‍යාපාර, ආගන්තුක සත්කාරය, කිරි කර්මාන්තය හා කලා' },
    career: { en: 'Entertainment, hospitality, public relations', si: 'විනෝදාස්වාදය, ආගන්තුක සත්කාරය හා මහජන සම්බන්ධතා' },
    relationships: { en: 'Deep romantic bonds; nurturing partnerships', si: 'ගැඹුරු ප්‍රේම බැඳීම්; රැකබලා ගන්නා හවුල්කාරිත්ව' },
    ratingMod: 1,
  },
  'Venus-Saturn': {
    theme: { en: 'Shukra-Shani — disciplined love and long-term relationships', si: 'ශුක්‍ර-ශනි — විනයගරුක ආදරය හා දිගු කාලීන සම්බන්ධතා' },
    health: { en: 'Chronic reproductive or kidney issues possible', si: 'නිදන්ගත ප්‍රජනන හෝ වකුගඩු ගැටලු ඇති විය හැක' },
    wealth: { en: 'Slow steady accumulation; real estate and industrial gains', si: 'මන්දගාමී ස්ථාවර ධන රැස්කිරීමක්; දේපළ හා කාර්මික ලාභ' },
    career: { en: 'Long-term creative projects, law, real estate', si: 'දිගු කාලීන නිර්මාණශීලී ව්‍යාපෘති, නීතිය හා දේපළ වෙළඳාම' },
    relationships: { en: 'Serious commitments; age-gap relationships possible', si: 'බැරෑරුම් කැපවීම්; වයස් පරතරයක් සහිත සම්බන්ධතා ඇති විය හැක' },
    warning: { en: 'Delays in relationships and pleasures — patience required', si: 'සම්බන්ධතාවල හා සැප සම්පත්වල ප්‍රමාද ඇති වේ — ඉවසීම අවශ්‍යය' },
    ratingMod: 0,
  },
  'Venus-Mars': {
    theme: { en: 'Shukra-Mangal — passionate energy and creative power', si: 'ශුක්‍ර-කුජ — ආශාවෙන් පිරි ශක්තිය හා නිර්මාණශීලී බලය' },
    health: { en: 'High energy; temper and accident risk rises', si: 'ශක්තිය ඉහළය; කෝපය හා අනතුරු අවදානම වැඩි වේ' },
    wealth: { en: 'Property and artistic ventures are profitable', si: 'දේපළ හා කලාත්මක ව්‍යාපෘති ලාභදායීය' },
    career: { en: 'Sports, arts, real estate, engineering all favored', si: 'ක්‍රීඩා, කලා, දේපළ වෙළඳාම හා ඉංජිනේරු විද්‍යාව හිතකරය' },
    relationships: { en: 'Intense romance; passion can lead to conflict', si: 'තීව්‍ර ප්‍රේමය; ආශාව නිසා ගැටුම් ඇති විය හැක' },
    warning: { en: 'Manage anger in relationships; avoid impulsive romantic decisions', si: 'සම්බන්ධතාවලදී කෝපය පාලනය කර ගන්න; හදිසි ප්‍රේම තීරණ වළක්වන්න' },
    ratingMod: 0,
  },
  'Venus-Rahu': {
    theme: { en: 'Shukra-Rahu — obsessive attraction and unconventional pleasures', si: 'ශුක්‍ර-රාහු — ඇලී ගැලී යන ආකර්ෂණය හා සම්ප්‍රදායික නොවන සුඛය' },
    health: { en: 'Reproductive and skin health may fluctuate', si: 'ප්‍රජනන හා සමේ සෞඛ්‍යය උච්චාවචනය විය හැක' },
    wealth: { en: 'Foreign luxury goods, technology, unconventional income', si: 'විදේශීය සුඛෝපභෝගී භාණ්ඩ, තාක්ෂණය හා සම්ප්‍රදායික නොවන ආදායම්' },
    career: { en: 'Foreign markets, technology arts, media career', si: 'විදේශ වෙළඳපොළ, තාක්ෂණික කලා හා මාධ්‍ය වෘත්තිය' },
    relationships: { en: 'Unusual or unconventional romantic attractions', si: 'අසාමාන්‍ය හෝ සම්ප්‍රදායික නොවන ප්‍රේම ආකර්ෂණයන්' },
    warning: { en: 'Temptation to overindulge or pursue forbidden pleasures', si: 'අධික ලෙස විඳීමට හෝ තහනම් සුඛය පසුපස යාමට පෙළඹවීමක් ඇති වේ' },
    ratingMod: -1,
  },
  'Venus-Ketu': {
    theme: { en: 'Shukra-Ketu — spiritual detachment from material pleasures', si: 'ශුක්‍ර-කේතු — භෞතික සුඛයෙන් අධ්‍යාත්මික වෙන්වීම' },
    health: { en: 'Reproductive concerns; spiritual healing recommended', si: 'ප්‍රජනන ගැටලු; අධ්‍යාත්මික සුවකිරීම නිර්දේශ කෙරේ' },
    wealth: { en: 'Material wealth may feel unsatisfying despite gains', si: 'ලාභ ලැබුණත් භෞතික ධනයෙන් තෘප්තියක් නොදැනිය හැක' },
    career: { en: 'Spiritual arts, healing, research', si: 'අධ්‍යාත්මික කලා, සුවකිරීම හා පර්යේෂණ' },
    relationships: { en: 'Detachment from relationships; karmic connections', si: 'සම්බන්ධතාවලින් වෙන් වීමක්; කර්ම බැඳීම්' },
    ratingMod: -1,
  },

  // ─── Saturn combinations ─────────────────────────────────────────────────
  'Saturn-Saturn': {
    theme: { en: 'Double Shani — intense karma, discipline, and transformation', si: 'ද්විගුණ ශනි — තීව්‍ර කර්මය, විනය හා පරිවර්තනය' },
    health: { en: 'Chronic issues surface; bones, joints, depression risk', si: 'නිදන්ගත රෝග මතු වේ; අස්ථි, සන්ධි හා අවපීඩන අවදානම' },
    wealth: { en: 'Hard work required; slow gains through service industries', si: 'වෙහෙස මහන්සි විය යුතුය; සේවා කර්මාන්ත හරහා මන්දගාමී ලාභ' },
    career: { en: 'Service, labor, mining, agriculture, administration', si: 'සේවා කටයුතු, ශ්‍රමය, පතල් කැණීම, කෘෂිකර්මය හා පරිපාලනය' },
    relationships: { en: 'Isolation possible; karmic relationship obligations', si: 'තනි වීමට ඉඩ ඇත; කර්මය හා බැඳුණු සම්බන්ධතා යුතුකම්' },
    warning: { en: 'Sade Sati-like pressure — this is a period of hard karmic lessons', si: 'සාඩේ සාති වැනි පීඩනයක් — මෙය දුෂ්කර කර්ම පාඩම් ලබන කාලයකි' },
    ratingMod: -2,
  },
  'Saturn-Rahu': {
    theme: { en: 'Shani-Rahu — karmic disruption and sudden obstacles', si: 'ශනි-රාහු — කර්මය හා බැඳුණු කඩාකප්පල් වීම් හා හදිසි බාධක' },
    health: { en: 'Mysterious chronic ailments; respiratory and skin issues', si: 'හඳුනාගත නොහැකි නිදන්ගත ආබාධ; ශ්වසන හා සමේ ගැටලු' },
    wealth: { en: 'Unexpected financial reversals; avoid speculation completely', si: 'අනපේක්ෂිත මූල්‍ය පසුබෑම්; සමපේක්ෂණය සම්පූර්ණයෙන් වළක්වන්න' },
    career: { en: 'Major upheavals at work; hidden enemies surface', si: 'සේවා ස්ථානයේ විශාල කැළඹීම්; සැඟවුණු සතුරන් මතු වේ' },
    relationships: { en: 'Relationship strain; isolation and misunderstandings', si: 'සම්බන්ධතාවල ආතතිය; තනිකම හා වැරදි වැටහීම්' },
    warning: { en: 'One of the most challenging combinations — extreme caution advised', si: 'වඩාත්ම අභියෝගාත්මක එකතුවලින් එකකි — දැඩි ප්‍රවේශමක් අවශ්‍යය' },
    ratingMod: -2,
  },
  'Saturn-Ketu': {
    theme: { en: 'Shani-Ketu — deep karma, losses and spiritual awakening', si: 'ශනි-කේතු — ගැඹුරු කර්මය, පාඩු හා අධ්‍යාත්මික අවදිවීම' },
    health: { en: 'Chronic and mysterious health issues; hospital risk', si: 'නිදන්ගත හා හඳුනාගත නොහැකි සෞඛ්‍ය ගැටලු; රෝහල්ගත වීමේ අවදානම' },
    wealth: { en: 'Financial losses through misfortune; past karma surfaces', si: 'අවාසනාව නිසා මූල්‍ය පාඩු; පෙර කර්මය මතු වේ' },
    career: { en: 'Career obstacles; forced changes and restructuring', si: 'වෘත්තීය බාධක; බලෙන් සිදු වන වෙනස්කම් හා ප්‍රතිව්‍යුහගත කිරීම්' },
    relationships: { en: 'Loss of loved ones or major separations possible', si: 'ආදරණීයයන් අහිමි වීමට හෝ විශාල වෙන්වීම්වලට ඉඩ ඇත' },
    warning: { en: 'Significant karmic clearing — spiritual practice is essential', si: 'සැලකිය යුතු කර්ම ගෙවීමක් — අධ්‍යාත්මික පිළිවෙත් අත්‍යවශ්‍යය' },
    ratingMod: -2,
  },
  'Saturn-Mars': {
    theme: { en: 'Shani-Mangal — conflict between effort and obstruction', si: 'ශනි-කුජ — උත්සාහය හා බාධාව අතර ගැටුම' },
    health: { en: 'Accidents, inflammation, and chronic fatigue risk', si: 'අනතුරු, දැවිලි තත්ත්ව හා නිදන්ගත වෙහෙස ඇතිවීමේ අවදානම' },
    wealth: { en: 'Hard work yields mixed results; property disputes possible', si: 'වෙහෙස මහන්සියෙන් මිශ්‍ර ප්‍රතිඵල; දේපළ ආරවුල් ඇති විය හැක' },
    career: { en: 'Conflicts with authority; discipline required for progress', si: 'බලධාරීන් සමඟ ගැටුම්; ප්‍රගතියට විනය අවශ්‍යය' },
    relationships: { en: 'Arguments and aggression in relationships', si: 'සම්බන්ධතාවල තර්ක හා ආක්‍රමණශීලී හැසිරීම්' },
    warning: { en: 'Manage anger and impatience; avoid legal and property disputes', si: 'කෝපය හා නොඉවසිලිමත්කම පාලනය කර ගන්න; නීතිමය හා දේපළ ආරවුල් වළක්වන්න' },
    ratingMod: -1,
  },
  'Saturn-Sun': {
    theme: { en: 'Shani-Surya — ego meets karma; authority challenged', si: 'ශනි-සූර්ය — අහංකාරය කර්මය හමු වේ; නිලබලය අභියෝගයට ලක් වේ' },
    health: { en: 'Vitality may dip; spine and heart need care', si: 'ජීවශක්තිය අඩු විය හැක; කොඳු ඇට පෙළ හා හෘදය ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Government or authority-related financial setbacks', si: 'රජය හෝ බලධාරීන් ආශ්‍රිත මූල්‍ය පසුබෑම්' },
    career: { en: 'Conflicts with superiors; career restructuring likely', si: 'ඉහළ නිලධාරීන් සමඟ ගැටුම්; වෘත්තීය ප්‍රතිව්‍යුහගත වීමකට ඉඩ ඇත' },
    relationships: { en: 'Father relationship strained; ego clashes at home', si: 'පියා සමඟ සම්බන්ධය ආතතියට පත් වේ; නිවසේ අහංකාර ගැටුම්' },
    warning: { en: 'Avoid power struggles with authority; humility is the key', si: 'බලධාරීන් සමඟ බල අරගල වළක්වන්න; නිහතමානිකම ප්‍රධාන යතුරයි' },
    ratingMod: -1,
  },
  'Saturn-Moon': {
    theme: { en: 'Shani-Chandra — emotional suppression and mental challenges', si: 'ශනි-චන්ද්‍ර — හැඟීම් යටපත් වීම හා මානසික අභියෝග' },
    health: { en: 'Depression, anxiety, and sleep disorders risk', si: 'අවපීඩනය, කනස්සල්ල හා නින්ද ආබාධ ඇතිවීමේ අවදානම' },
    wealth: { en: 'Emotionally-driven financial decisions may backfire', si: 'හැඟීම් මත ගන්නා මූල්‍ය තීරණ අහිතකර විය හැක' },
    career: { en: 'Work feels burdensome; lack of recognition', si: 'වැඩ බරක් ලෙස දැනේ; නිසි පිළිගැනීමක් නොලැබේ' },
    relationships: { en: 'Emotional distance in relationships; mother-figure conflicts', si: 'සම්බන්ධතාවල හැඟීම්බර දුරස්ථභාවය; මව සමඟ ගැටුම්' },
    warning: { en: 'Mental health must be prioritized — seek support if needed', si: 'මානසික සෞඛ්‍යයට ප්‍රමුඛත්වය දිය යුතුය — අවශ්‍ය නම් සහය ලබා ගන්න' },
    ratingMod: -1,
  },
  'Saturn-Jupiter': {
    theme: { en: 'Shani-Guru — wisdom through discipline and karmic lessons', si: 'ශනි-ගුරු — විනය හා කර්ම පාඩම් හරහා ලැබෙන ඥානය' },
    health: { en: 'Liver and joints need attention; moderation in diet', si: 'අක්මාව හා සන්ධි ගැන අවධානය අවශ්‍යය; ආහාරයේ සංයමය රැක ගන්න' },
    wealth: { en: 'Slow but steady; long-term investments and property gains', si: 'මන්දගාමී නමුත් ස්ථාවර; දිගු කාලීන ආයෝජන හා දේපළ ලාභ' },
    career: { en: 'Senior professional roles; judiciary and administration', si: 'ජ්‍යෙෂ්ඨ වෘත්තීය තනතුරු; විනිශ්චය සේවය හා පරිපාලනය' },
    relationships: { en: 'Serious, dharmic relationships; responsibilities to elders', si: 'බැරෑරුම්, ධාර්මික සම්බන්ධතා; වැඩිහිටියන් කෙරෙහි වගකීම්' },
    ratingMod: 0,
  },
  'Saturn-Venus': {
    theme: { en: 'Shani-Shukra — delayed pleasures and disciplined creativity', si: 'ශනි-ශුක්‍ර — ප්‍රමාද වන සුඛය හා විනයගරුක නිර්මාණශීලීත්වය' },
    health: { en: 'Reproductive and kidney health careful monitoring', si: 'ප්‍රජනන හා වකුගඩු සෞඛ්‍යය ප්‍රවේශමෙන් පරීක්ෂා කර බලන්න' },
    wealth: { en: 'Long-term creative projects pay off eventually', si: 'දිගු කාලීන නිර්මාණශීලී ව්‍යාපෘති අවසානයේ ප්‍රතිඵල දෙයි' },
    career: { en: 'Real estate, arts on long timelines, law', si: 'දේපළ වෙළඳාම, දිගු කාලයක් ගන්නා කලා කටයුතු හා නීතිය' },
    relationships: { en: 'Delayed marriage; serious long-term commitments', si: 'විවාහය ප්‍රමාද වේ; බැරෑරුම් දිගු කාලීන කැපවීම්' },
    ratingMod: 0,
  },
  'Saturn-Mercury': {
    theme: { en: 'Shani-Budha — methodical intelligence and careful planning', si: 'ශනි-බුධ — ක්‍රමවත් බුද්ධිය හා ප්‍රවේශම් සහගත සැලසුම්කරණය' },
    health: { en: 'Nervous system and skin care important', si: 'ස්නායු පද්ධතිය හා සමේ සත්කාරය වැදගත් වේ' },
    wealth: { en: 'Careful financial planning yields slow but reliable gains', si: 'ප්‍රවේශම් සහගත මූල්‍ය සැලසුම් මන්දගාමී නමුත් විශ්වාසදායක ලාභ දෙයි' },
    career: { en: 'Systematic, detail-oriented work excels', si: 'ක්‍රමවත්, සියුම් විස්තර සමඟ කරන වැඩ සාර්ථක වේ' },
    relationships: { en: 'Intellectual but emotionally distant connections', si: 'බුද්ධිමය නමුත් හැඟීම්බර වශයෙන් දුරස්ථ සම්බන්ධතා' },
    ratingMod: 0,
  },

  // ─── Rahu combinations ───────────────────────────────────────────────────
  'Rahu-Rahu': {
    theme: { en: 'Double Rahu — intense illusion, ambition and foreign influences', si: 'ද්විගුණ රාහු — තීව්‍ර මායාව, අභිලාෂය හා විදේශීය බලපෑම්' },
    health: { en: 'Mysterious and unusual health conditions; phobias', si: 'හඳුනාගත නොහැකි හා අසාමාන්‍ය සෞඛ්‍ය තත්ත්ව; භීතිකා' },
    wealth: { en: 'Foreign income; speculative gains with high risk', si: 'විදේශ ආදායම්; අධි අවදානම් සහිත සමපේක්ෂණ ලාභ' },
    career: { en: 'Technology, foreign work, politics, media at peak', si: 'තාක්ෂණය, විදේශ රැකියා, දේශපාලනය හා මාධ්‍ය උච්චතම මට්ටමේ' },
    relationships: { en: 'Obsessive or unusual relationships; in-law complexities', si: 'ඇලී ගැලී යන හෝ අසාමාන්‍ය සම්බන්ධතා; නෑදෑ පාර්ශ්වයේ සංකීර්ණතා' },
    warning: { en: 'Reality distortion is high — stay grounded and ethical', si: 'යථාර්ථය විකෘති වීමේ ඉඩ වැඩිය — යථාර්ථවාදීව හා සදාචාරාත්මකව සිටින්න' },
    ratingMod: -1,
  },
  'Rahu-Saturn': {
    theme: { en: 'Rahu-Shani — sudden karmic disruption and chronic obstacles', si: 'රාහු-ශනි — හදිසි කර්ම කැළඹීම් හා නිදන්ගත බාධක' },
    health: { en: 'Chronic mysterious ailments; mental health stress', si: 'නිදන්ගත, හඳුනාගත නොහැකි ආබාධ; මානසික ආතතිය' },
    wealth: { en: 'Unexpected losses; avoid all speculation', si: 'අනපේක්ෂිත පාඩු; සියලු සමපේක්ෂණ වළක්වන්න' },
    career: { en: 'Hidden enemies, workplace disruption, restructuring', si: 'සැඟවුණු සතුරන්, සේවා ස්ථානයේ කැළඹීම් හා ප්‍රතිව්‍යුහගත කිරීම්' },
    relationships: { en: 'Sudden separations; unusual karmic obligations', si: 'හදිසි වෙන්වීම්; අසාමාන්‍ය කර්ම යුතුකම්' },
    warning: { en: 'Most challenging sub-period — heightened vigilance required', si: 'වඩාත්ම අභියෝගාත්මක අන්තර් දශාව — දැඩි අවධානයක් අවශ්‍යය' },
    ratingMod: -2,
  },
  'Rahu-Mars': {
    theme: { en: 'Rahu-Mangal — explosive energy and reckless ambition', si: 'රාහු-කුජ — පුපුරන සුළු ශක්තිය හා නොසැලකිලිමත් අභිලාෂය' },
    health: { en: 'Accidents, infections, and impulsive health choices', si: 'අනතුරු, ආසාදන හා හදිසියේ ගන්නා සෞඛ්‍ය තීරණ' },
    wealth: { en: 'High-risk ventures; sudden gains and sudden losses', si: 'අධි අවදානම් ව්‍යාපෘති; හදිසි ලාභ මෙන්ම හදිසි පාඩු ද' },
    career: { en: 'Aggressive career moves; competition is fierce', si: 'ආක්‍රමණශීලී වෘත්තීය තීරණ; තරඟය දැඩිය' },
    relationships: { en: 'Passionate but volatile; conflicts with siblings', si: 'ආශාවෙන් පිරි නමුත් අස්ථිර; සහෝදරයන් සමඟ ගැටුම්' },
    warning: { en: 'Impulsive decisions can be costly — think before acting', si: 'හදිසි තීරණ මිල අධික විය හැක — ක්‍රියා කිරීමට පෙර සිතන්න' },
    ratingMod: -1,
  },
  'Rahu-Ketu': {
    theme: { en: 'Rahu-Ketu — nodal axis activated; destabilizing transformation', si: 'රාහු-කේතු — රාහු-කේතු අක්ෂය සක්‍රිය වේ; අස්ථිර කරන පරිවර්තනයක්' },
    health: { en: 'Strange ailments affecting both physical and mental health', si: 'ශාරීරික හා මානසික සෞඛ්‍යය දෙකටම බලපාන අමුතු ආබාධ' },
    wealth: { en: 'Financial instability; past karma affecting income', si: 'මූල්‍ය අස්ථිරතාව; පෙර කර්මය ආදායමට බලපායි' },
    career: { en: 'Career direction confusion; sudden unexpected changes', si: 'වෘත්තීය දිශාව අවුල් වේ; හදිසි අනපේක්ෂිත වෙනස්කම්' },
    relationships: { en: 'Past-life relationship karma surfaces forcefully', si: 'පෙර භවවල සම්බන්ධතා කර්මය බලවත් ලෙස මතු වේ' },
    warning: { en: 'Nodal period brings fated events — surrender and adapt', si: 'මෙම කාලය නියමිත සිදුවීම් ගෙන එයි — භාර වී ඒවාට හැඩ ගැසෙන්න' },
    ratingMod: -1,
  },
  'Rahu-Jupiter': {
    theme: { en: 'Rahu-Guru — ambition meets wisdom; ethics under pressure', si: 'රාහු-ගුරු — අභිලාෂය ඥානය හමු වේ; සදාචාරය පීඩනයට ලක් වේ' },
    health: { en: 'Liver and mysterious conditions; watch for excess', si: 'අක්මාව හා හඳුනාගත නොහැකි රෝග; අධික ලෙස කිසිවක් නොකරන්න' },
    wealth: { en: 'Ambitious financial schemes — some succeed, some backfire', si: 'අභිලාෂකාමී මූල්‍ය සැලසුම් — සමහරක් සාර්ථක වන අතර සමහරක් අහිතකර වේ' },
    career: { en: 'Foreign education, unconventional advisory roles', si: 'විදේශ අධ්‍යාපනය හා සම්ප්‍රදායික නොවන උපදේශන කටයුතු' },
    relationships: { en: 'Unusual teachers or mentors enter life', si: 'අසාමාන්‍ය ගුරුවරුන් හෝ මඟපෙන්වන්නන් ජීවිතයට පැමිණේ' },
    warning: { en: 'Maintain ethical standards despite tempting shortcuts', si: 'පෙළඹවන කෙටි මං තිබුණත් සදාචාර ප්‍රමිතීන් රැක ගන්න' },
    ratingMod: 0,
  },
  'Rahu-Venus': {
    theme: { en: 'Rahu-Shukra — obsessive attraction and material desire', si: 'රාහු-ශුක්‍ර — ඇලී ගැලී යන ආකර්ෂණය හා භෞතික ආශාව' },
    health: { en: 'Reproductive and addictive tendency watch', si: 'ප්‍රජනන සෞඛ්‍යය හා ඇබ්බැහි වීමේ නැඹුරුව ගැන අවධානය' },
    wealth: { en: 'Foreign luxury and technology income rises', si: 'විදේශීය සුඛෝපභෝගී හා තාක්ෂණික ආදායම් වැඩි වේ' },
    career: { en: 'Media, foreign markets, technology arts', si: 'මාධ්‍ය, විදේශ වෙළඳපොළ හා තාක්ෂණික කලා' },
    relationships: { en: 'Magnetic but potentially obsessive attractions', si: 'ආකර්ෂණීය නමුත් ඇලී ගැලී යා හැකි බැඳීම්' },
    ratingMod: 0,
  },
  'Rahu-Mercury': {
    theme: { en: 'Rahu-Budha — analytical brilliance meets unconventional thinking', si: 'රාහු-බුධ — විශ්ලේෂණාත්මක දීප්තිය සම්ප්‍රදායට වෙනස් චින්තනය හමු වේ' },
    health: { en: 'Nervous system under pressure; anxiety possible', si: 'ස්නායු පද්ධතිය පීඩනයට ලක් වේ; කනස්සල්ල ඇති විය හැක' },
    wealth: { en: 'Technology, foreign trade, unconventional business income', si: 'තාක්ෂණය, විදේශ වෙළඳාම හා සම්ප්‍රදායික නොවන ව්‍යාපාර ආදායම්' },
    career: { en: 'Innovation, foreign communication, digital entrepreneurship', si: 'නවෝත්පාදන, විදේශ සන්නිවේදනය හා ඩිජිටල් ව්‍යවසායකත්වය' },
    relationships: { en: 'Interesting intellectual connections; unusual friends', si: 'රසවත් බුද්ධිමය සම්බන්ධතා; අසාමාන්‍ය මිතුරන්' },
    ratingMod: 0,
  },
  'Rahu-Moon': {
    theme: { en: 'Rahu-Chandra — emotional turbulence and psychic sensitivity', si: 'රාහු-චන්ද්‍ර — හැඟීම්බර කැළඹීම හා අභ්‍යන්තර සංවේදිතාව' },
    health: { en: 'Mental health, anxiety, and emotional swings', si: 'මානසික සෞඛ්‍යය, කනස්සල්ල හා හැඟීම් උච්චාවචන' },
    wealth: { en: 'Public income with instability; emotional spending risk', si: 'අස්ථිර මහජන ආදායම්; හැඟීම් මත වියදම් කිරීමේ අවදානම' },
    career: { en: 'Media, public platforms, emotional intelligence roles', si: 'මාධ්‍ය, මහජන වේදිකා හා හැඟීම් තේරුම් ගැනීම අවශ්‍ය කාර්යයන්' },
    relationships: { en: 'Intense emotional bonds; mother-figure complications', si: 'තීව්‍ර හැඟීම්බර බැඳීම්; මව සමඟ සංකීර්ණතා' },
    warning: { en: 'Guard mental health carefully; avoid emotional extremes', si: 'මානසික සෞඛ්‍යය ප්‍රවේශමෙන් රැක ගන්න; හැඟීම්වල අන්ත වළක්වන්න' },
    ratingMod: -1,
  },
  'Rahu-Sun': {
    theme: { en: 'Rahu-Surya — eclipse of authority; ambition and ego clash', si: 'රාහු-සූර්ය — නිලබලයට ග්‍රහණයක්; අභිලාෂය හා අහංකාරය ගැටේ' },
    health: { en: 'Heart and vitality fluctuations; mysterious fevers', si: 'හෘදය හා ජීවශක්තිය උච්චාවචනය වේ; හඳුනාගත නොහැකි උණ' },
    wealth: { en: 'Government-related income uncertain; authority friction', si: 'රජය ආශ්‍රිත ආදායම් අවිනිශ්චිතයි; බලධාරීන් සමඟ ඝට්ටන' },
    career: { en: 'Conflicts with authority; sudden rise or fall in career', si: 'බලධාරීන් සමඟ ගැටුම්; වෘත්තියේ හදිසි නැගීමක් හෝ වැටීමක්' },
    relationships: { en: 'Father relationship strained; ego conflict with superiors', si: 'පියා සමඟ සම්බන්ධය ආතතියට පත් වේ; ඉහළ නිලධාරීන් සමඟ අහංකාර ගැටුම්' },
    warning: { en: 'Ego must be checked — avoid power struggles with authority', si: 'අහංකාරය පාලනය කර ගත යුතුය — බලධාරීන් සමඟ බල අරගල වළක්වන්න' },
    ratingMod: -1,
  },

  // ─── Ketu combinations ───────────────────────────────────────────────────
  'Ketu-Ketu': {
    theme: { en: 'Double Ketu — intense spiritual detachment and karmic completion', si: 'ද්විගුණ කේතු — තීව්‍ර අධ්‍යාත්මික වෙන්වීම හා කර්මය සම්පූර්ණ වීම' },
    health: { en: 'Mysterious ailments; surgeries and past-life health karma', si: 'හඳුනාගත නොහැකි ආබාධ; සැත්කම් හා පෙර භවයේ සෞඛ්‍ය කර්මය' },
    wealth: { en: 'Material losses; detachment from wealth is the lesson', si: 'භෞතික පාඩු; ධනයෙන් වෙන් වීම මෙහි පාඩමයි' },
    career: { en: 'Career dissolution; spiritual or research calling emerges', si: 'වෘත්තිය බිඳ වැටේ; අධ්‍යාත්මික හෝ පර්යේෂණ කැඳවීමක් මතු වේ' },
    relationships: { en: 'Isolation from worldly relationships; spiritual bonds', si: 'ලෞකික සම්බන්ධතාවලින් වෙන් වීම; අධ්‍යාත්මික බැඳීම්' },
    ratingMod: -2,
  },
  'Ketu-Mars': {
    theme: { en: 'Ketu-Mangal — sudden accidents and spiritual courage', si: 'කේතු-කුජ — හදිසි අනතුරු හා අධ්‍යාත්මික ධෛර්යය' },
    health: { en: 'Injuries, surgeries, and mysterious fevers', si: 'තුවාල, සැත්කම් හා හඳුනාගත නොහැකි උණ' },
    wealth: { en: 'Property disputes; sudden material losses', si: 'දේපළ ආරවුල්; හදිසි භෞතික පාඩු' },
    career: { en: 'Technical and investigative work; sudden career changes', si: 'තාක්ෂණික හා විමර්ශන කටයුතු; හදිසි වෘත්තීය වෙනස්කම්' },
    relationships: { en: 'Sibling conflicts; past-life competitive karma', si: 'සහෝදර ගැටුම්; පෙර භවයේ තරඟකාරී කර්මය' },
    warning: { en: 'Accidents are more likely — extra physical caution required', si: 'අනතුරු සිදු වීමේ ඉඩ වැඩිය — අමතර ශාරීරික ප්‍රවේශමක් අවශ්‍යය' },
    ratingMod: -1,
  },
  'Ketu-Rahu': {
    theme: { en: 'Ketu-Rahu — nodal reversal; fated disruptions and surrenders', si: 'කේතු-රාහු — අක්ෂය හැරවීම; නියමිත කැළඹීම් හා භාර වීම්' },
    health: { en: 'Health unpredictability; stress-related conditions', si: 'සෞඛ්‍යය අනපේක්ෂිතයි; ආතතිය ආශ්‍රිත රෝග තත්ත්ව' },
    wealth: { en: 'Financial instability from unexpected karmic sources', si: 'අනපේක්ෂිත කර්ම හේතූන් නිසා මූල්‍ය අස්ථිරතාව' },
    career: { en: 'Career upheavals; role changes or losses', si: 'වෘත්තීය කැළඹීම්; තනතුරු වෙනස් වීම හෝ අහිමි වීම' },
    relationships: { en: 'Fated meetings and separations; strong past-life pull', si: 'නියමිත හමුවීම් හා වෙන්වීම්; පෙර භවයේ ප්‍රබල ඇදීමක්' },
    warning: { en: 'Nodal sub-period in Ketu Mahadasha is especially intense', si: 'කේතු මහා දශාව තුළ මෙම අන්තර් දශාව විශේෂයෙන් තීව්‍රය' },
    ratingMod: -1,
  },
  'Ketu-Jupiter': {
    theme: { en: 'Ketu-Guru — spiritual wisdom and detachment from worldly success', si: 'කේතු-ගුරු — අධ්‍යාත්මික ඥානය හා ලෞකික සාර්ථකත්වයෙන් වෙන් වීම' },
    health: { en: 'Liver and mysterious conditions; healing through spirituality', si: 'අක්මාව හා හඳුනාගත නොහැකි රෝග; අධ්‍යාත්මිකත්වය හරහා සුවය' },
    wealth: { en: 'Wealth from spiritual or research work; material detachment', si: 'අධ්‍යාත්මික හෝ පර්යේෂණ කටයුතුවලින් ධනය; භෞතික දෑින් වෙන් වීම' },
    career: { en: 'Spiritual teaching, occult research, healing arts', si: 'අධ්‍යාත්මික ඉගැන්වීම, ගුප්ත විද්‍යා පර්යේෂණ හා සුවකිරීමේ කලා' },
    relationships: { en: 'Wise, detached relationships; guru-student connections', si: 'ඥානවන්ත, නොඇලෙන සම්බන්ධතා; ගුරු-ශිෂ්‍ය බැඳීම්' },
    bonus: { en: 'Excellent for spiritual growth and past-life wisdom retrieval', si: 'අධ්‍යාත්මික වර්ධනයට හා පෙර භවයේ ඥානය නැවත ලබා ගැනීමට විශිෂ්ටයි' },
    ratingMod: 0,
  },
  'Ketu-Saturn': {
    theme: { en: 'Ketu-Shani — karmic clearing through hardship', si: 'කේතු-ශනි — දුෂ්කරතා හරහා කර්මය ගෙවී යාම' },
    health: { en: 'Chronic and mysterious ailments; isolation risk', si: 'නිදන්ගත හා හඳුනාගත නොහැකි ආබාධ; තනි වීමේ අවදානම' },
    wealth: { en: 'Material losses as karmic correction', si: 'කර්ම නිවැරදි කිරීමක් ලෙස භෞතික පාඩු' },
    career: { en: 'Career restructuring; forced detachment from old roles', si: 'වෘත්තීය ප්‍රතිව්‍යුහගත වීම; පැරණි තනතුරුවලින් බලෙන් වෙන් වීම' },
    relationships: { en: 'Loss of relationships through karma', si: 'කර්මය හේතුවෙන් සම්බන්ධතා අහිමි වීම' },
    warning: { en: 'Most intense karmic combination — spiritual practice is essential', si: 'තීව්‍රතම කර්ම එකතුව — අධ්‍යාත්මික පිළිවෙත් අත්‍යවශ්‍යය' },
    ratingMod: -2,
  },
  'Ketu-Mercury': {
    theme: { en: 'Ketu-Budha — intuitive intelligence and analytical detachment', si: 'කේතු-බුධ — ඉවෙන් ලැබෙන බුද්ධිය හා නොඇලෙන විශ්ලේෂණය' },
    health: { en: 'Nervous system sensitivity; skin and respiratory issues', si: 'ස්නායු පද්ධතියේ සංවේදිතාව; සමේ හා ශ්වසන ගැටලු' },
    wealth: { en: 'Income from research, writing, or spiritual services', si: 'පර්යේෂණ, ලේඛන හෝ අධ්‍යාත්මික සේවාවලින් ආදායම' },
    career: { en: 'Research, writing, investigative journalism, occult', si: 'පර්යේෂණ, ලේඛන, විමර්ශන මාධ්‍යවේදය හා ගුප්ත විද්‍යාව' },
    relationships: { en: 'Intellectual but detached connections', si: 'බුද්ධිමය නමුත් නොඇලෙන සම්බන්ධතා' },
    ratingMod: 0,
  },
  'Ketu-Venus': {
    theme: { en: 'Ketu-Shukra — spiritual detachment from sensual pleasures', si: 'කේතු-ශුක්‍ර — ඉන්ද්‍රිය සුඛයෙන් අධ්‍යාත්මික වෙන් වීම' },
    health: { en: 'Reproductive and mysterious health concerns', si: 'ප්‍රජනන හා හඳුනාගත නොහැකි සෞඛ්‍ය ගැටලු' },
    wealth: { en: 'Material pleasures feel unfulfilling despite income', si: 'ආදායම ලැබුණත් භෞතික සුඛයෙන් තෘප්තියක් නොදැනේ' },
    career: { en: 'Spiritual arts, healing, research-based creative work', si: 'අධ්‍යාත්මික කලා, සුවකිරීම හා පර්යේෂණ මත පදනම් වූ නිර්මාණ කටයුතු' },
    relationships: { en: 'Karmic romantic connections; relationships feel destined but difficult', si: 'කර්මය හා බැඳුණු ප්‍රේම සම්බන්ධතා; ඒවා නියමිත නමුත් දුෂ්කර ලෙස දැනේ' },
    ratingMod: -1,
  },
  'Ketu-Sun': {
    theme: { en: 'Ketu-Surya — ego dissolution and spiritual authority', si: 'කේතු-සූර්ය — අහංකාරය දිය වී යාම හා අධ්‍යාත්මික බලය' },
    health: { en: 'Vitality fluctuations; mysterious or viral conditions', si: 'ජීවශක්තිය උච්චාවචනය වේ; හඳුනාගත නොහැකි හෝ වෛරස රෝග' },
    wealth: { en: 'Government or authority-related income affected', si: 'රජය හෝ බලධාරීන් ආශ්‍රිත ආදායම්වලට බලපෑමක් වේ' },
    career: { en: 'Leadership roles may feel hollow; spiritual authority emerges', si: 'නායකත්ව තනතුරු හිස් ලෙස දැනිය හැක; අධ්‍යාත්මික බලයක් මතු වේ' },
    relationships: { en: 'Father relationship karmic; authority figures challenge you', si: 'පියා සමඟ සම්බන්ධය කර්මය හා බැඳේ; බලධාරීන් ඔබට අභියෝග කරයි' },
    ratingMod: -1,
  },
  'Ketu-Moon': {
    theme: { en: 'Ketu-Chandra — emotional detachment and intuitive depths', si: 'කේතු-චන්ද්‍ර — හැඟීම්බර වෙන් වීම හා ඉවේ ගැඹුර' },
    health: { en: 'Mental health, depression, and emotional numbness', si: 'මානසික සෞඛ්‍යය, අවපීඩනය හා හැඟීම් හිරි වැටීම' },
    wealth: { en: 'Emotional spending; public income fluctuates', si: 'හැඟීම් මත වියදම් කිරීම; මහජන ආදායම් උච්චාවචනය වේ' },
    career: { en: 'Healing, research, spiritual counseling roles', si: 'සුවකිරීම, පර්යේෂණ හා අධ්‍යාත්මික උපදේශන කටයුතු' },
    relationships: { en: 'Emotional distance; mother-karma surfaces', si: 'හැඟීම්බර දුරස්ථභාවය; මව හා බැඳුණු කර්මය මතු වේ' },
    warning: { en: 'Guard against depression and emotional isolation', si: 'අවපීඩනයෙන් හා හැඟීම්බර හුදෙකලාවෙන් ආරක්ෂා වන්න' },
    ratingMod: -1,
  },

  // ─── Sun combinations ────────────────────────────────────────────────────
  'Sun-Sun': {
    theme: { en: 'Double Surya — peak authority, recognition and self-expression', si: 'ද්විගුණ සූර්ය — නිලබලය, පිළිගැනීම හා ස්වයං ප්‍රකාශනයේ උච්චතම අවස්ථාව' },
    health: { en: 'Heart and eye health must be monitored carefully', si: 'හෘදය හා ඇස්වල සෞඛ්‍යය ප්‍රවේශමෙන් පරීක්ෂා කර බැලිය යුතුය' },
    wealth: { en: 'Government income, leadership bonuses, gold investments', si: 'රාජ්‍ය ආදායම්, නායකත්ව දීමනා හා රන් ආයෝජන' },
    career: { en: 'Leadership, government, and political career at its peak', si: 'නායකත්වය, රාජ්‍ය සේවය හා දේශපාලන වෘත්තිය උච්චතම මට්ටමේ' },
    relationships: { en: 'Ego can dominate — practice humility with loved ones', si: 'අහංකාරය ඉස්මතු විය හැක — ආදරණීයයන් සමඟ නිහතමානිකම පුරුදු කරන්න' },
    ratingMod: 1,
  },
  'Sun-Moon': {
    theme: { en: 'Surya-Chandra — balancing ego and emotion; public recognition', si: 'සූර්ය-චන්ද්‍ර — අහංකාරය හා හැඟීම් සමතුලිත කිරීම; මහජන පිළිගැනීම' },
    health: { en: 'Emotional and physical energy fluctuates; rest is key', si: 'හැඟීම්බර හා ශාරීරික ශක්තිය උච්චාවචනය වේ; විවේකය ප්‍රධානය' },
    wealth: { en: 'Public-facing income grows; real estate opportunities', si: 'මහජනතාව ආශ්‍රිත ආදායම් වර්ධනය වේ; දේපළ අවස්ථා ලැබේ' },
    career: { en: 'Public roles, government, and emotional leadership', si: 'මහජන තනතුරු, රාජ්‍ය සේවය හා හැඟීම් තේරුම් ගන්නා නායකත්වය' },
    relationships: { en: 'Family dynamics become important; work-life balance challenge', si: 'පවුලේ තත්ත්වයන් වැදගත් වේ; රැකියාව හා ජීවිතය සමතුලිත කිරීම අභියෝගයකි' },
    ratingMod: 1,
  },
  'Sun-Mars': {
    theme: { en: 'Surya-Mangal — dynamic energy and bold leadership action', si: 'සූර්ය-කුජ — ගතික ශක්තිය හා නිර්භීත නායකත්ව ක්‍රියාව' },
    health: { en: 'Fever, blood pressure, and injury risk; channel energy well', si: 'උණ, රුධිර පීඩනය හා තුවාල අවදානම; ශක්තිය නිසි ලෙස යොදවන්න' },
    wealth: { en: 'Government contracts, property, technical income', si: 'රාජ්‍ය කොන්ත්‍රාත්, දේපළ හා තාක්ෂණික ආදායම්' },
    career: { en: 'Military, sports, government, engineering — all peak', si: 'හමුදා සේවය, ක්‍රීඩා, රාජ්‍ය සේවය හා ඉංජිනේරු විද්‍යාව උච්චතම මට්ටමේ' },
    relationships: { en: 'Assertive but may be domineering; sibling dynamics active', si: 'ස්ථිර නමුත් ආධිපත්‍යය දැරිය හැක; සහෝදර සම්බන්ධතා ක්‍රියාශීලීය' },
    ratingMod: 1,
  },
  'Sun-Jupiter': {
    theme: { en: 'Surya-Guru — divine blessing on authority and wisdom', si: 'සූර්ය-ගුරු — නිලබලයට හා ඥානයට දේව ආශිර්වාදය' },
    health: { en: 'Strong vitality; liver and weight moderation needed', si: 'ජීවශක්තිය ප්‍රබලයි; අක්මාව හා ශරීර බර සම්බන්ධයෙන් සංයමය අවශ්‍යය' },
    wealth: { en: 'Government income, advisory fees, dharmic wealth', si: 'රාජ්‍ය ආදායම්, උපදේශන ගාස්තු හා ධාර්මික ධනය' },
    career: { en: 'Academic leadership, judicial roles, government advisory', si: 'අධ්‍යයන නායකත්වය, විනිශ්චය තනතුරු හා රාජ්‍ය උපදේශන කටයුතු' },
    relationships: { en: 'Father and mentor relationships are blessed', si: 'පියා හා මඟපෙන්වන්නන් සමඟ සම්බන්ධතා ආශිර්වාද ලබයි' },
    bonus: { en: 'Excellent for getting recognition and honor in career', si: 'වෘත්තියේ පිළිගැනීම හා ගෞරවය ලබා ගැනීමට විශිෂ්ටයි' },
    ratingMod: 1,
  },
  'Sun-Saturn': {
    theme: { en: 'Surya-Shani — authority challenged by karma and discipline', si: 'සූර්ය-ශනි — කර්මය හා විනය නිසා නිලබලය අභියෝගයට ලක් වේ' },
    health: { en: 'Spine, heart, and chronic fatigue risk', si: 'කොඳු ඇට පෙළ, හෘදය හා නිදන්ගත වෙහෙස ඇතිවීමේ අවදානම' },
    wealth: { en: 'Hard-earned income; government dealings face delays', si: 'වෙහෙසෙන් උපයන ආදායම්; රාජ්‍ය කටයුතු ප්‍රමාද වේ' },
    career: { en: 'Authority conflicts; career requires extra effort', si: 'බලධාරීන් සමඟ ගැටුම්; වෘත්තියට අමතර වෙහෙසක් අවශ්‍යය' },
    relationships: { en: 'Father relationship strained; responsibility burden increases', si: 'පියා සමඟ සම්බන්ධය ආතතියට පත් වේ; වගකීම් බර වැඩි වේ' },
    warning: { en: 'Avoid ego clashes with authority figures; humility is essential', si: 'බලධාරීන් සමඟ අහංකාර ගැටුම් වළක්වන්න; නිහතමානිකම අත්‍යවශ්‍යය' },
    ratingMod: -1,
  },
  'Sun-Mercury': {
    theme: { en: 'Surya-Budha — Budhaditya yoga; intelligence and communication', si: 'සූර්ය-බුධ — බුධාදිත්‍ය යෝගය; බුද්ධිය හා සන්නිවේදනය' },
    health: { en: 'Eye health and nervous system need attention', si: 'ඇස්වල සෞඛ්‍යය හා ස්නායු පද්ධතිය ගැන අවධානය අවශ්‍යය' },
    wealth: { en: 'Communication-based income; government contracts', si: 'සන්නිවේදනය මත පදනම් වූ ආදායම්; රාජ්‍ය කොන්ත්‍රාත්' },
    career: { en: 'Writing, government communication, analytical leadership', si: 'ලේඛන කලාව, රාජ්‍ය සන්නිවේදනය හා විශ්ලේෂණාත්මක නායකත්වය' },
    relationships: { en: 'Intellectual connections; younger people bring opportunities', si: 'බුද්ධිමය සම්බන්ධතා; තරුණ පිරිස අවස්ථා ගෙන එයි' },
    bonus: { en: 'Budhaditya yoga — intelligence and fame through communication', si: 'බුධාදිත්‍ය යෝගය — සන්නිවේදනය හරහා බුද්ධිය හා කීර්තිය' },
    ratingMod: 1,
  },
  'Sun-Venus': {
    theme: { en: 'Surya-Shukra — authority meets art; professional recognition', si: 'සූර්ය-ශුක්‍ර — නිලබලය කලාව හමු වේ; වෘත්තීය පිළිගැනීම' },
    health: { en: 'Heart and kidneys need monitoring; eyes watch', si: 'හෘදය හා වකුගඩු පරීක්ෂා කර බැලිය යුතුය; ඇස් ගැන ද අවධානය' },
    wealth: { en: 'Arts income, government recognition, luxury purchases', si: 'කලා ආදායම්, රාජ්‍ය පිළිගැනීම හා සුඛෝපභෝගී භාණ්ඩ මිලදී ගැනීම' },
    career: { en: 'Arts-government interface, luxury brands, political careers', si: 'කලාව හා රජය එක් වන ක්ෂේත්‍ර, සුඛෝපභෝගී වෙළඳ නාම හා දේශපාලන වෘත්ති' },
    relationships: { en: 'Creative romantic connections; spouse from different background', si: 'නිර්මාණශීලී ප්‍රේම සම්බන්ධතා; වෙනස් පසුබිමකින් කලත්‍රයෙක්' },
    ratingMod: 0,
  },
  'Sun-Rahu': {
    theme: { en: 'Surya-Rahu — eclipse energy; ambition and authority clashing', si: 'සූර්ය-රාහු — ග්‍රහණ ශක්තිය; අභිලාෂය හා නිලබලය ගැටේ' },
    health: { en: 'Mysterious fever, eye issues, vitality fluctuations', si: 'හඳුනාගත නොහැකි උණ, අක්ෂි ආබාධ හා ජීවශක්ති උච්චාවචන' },
    wealth: { en: 'Government income uncertain; foreign income rises', si: 'රාජ්‍ය ආදායම් අවිනිශ්චිතයි; විදේශ ආදායම් වැඩි වේ' },
    career: { en: 'Sudden career changes; ambition exceeds caution', si: 'හදිසි වෘත්තීය වෙනස්කම්; අභිලාෂය ප්‍රවේශම ඉක්මවා යයි' },
    relationships: { en: 'Father relationship complicated; authority conflicts', si: 'පියා සමඟ සම්බන්ධය සංකීර්ණ වේ; බලධාරීන් සමඟ ගැටුම්' },
    warning: { en: 'Eclipse combination — unexpected events and authority friction', si: 'ග්‍රහණ එකතුවකි — අනපේක්ෂිත සිදුවීම් හා බලධාරීන් සමඟ ඝට්ටන' },
    ratingMod: -1,
  },
  'Sun-Ketu': {
    theme: { en: 'Surya-Ketu — spiritual authority and ego dissolution', si: 'සූර්ය-කේතු — අධ්‍යාත්මික බලය හා අහංකාරය දිය වී යාම' },
    health: { en: 'Mysterious vitality issues; viral and past-karma ailments', si: 'හඳුනාගත නොහැකි ජීවශක්ති ගැටලු; වෛරස හා පෙර කර්ම ආබාධ' },
    wealth: { en: 'Government income affected; spiritual income rises', si: 'රාජ්‍ය ආදායම්වලට බලපෑමක් වේ; අධ්‍යාත්මික ආදායම් වැඩි වේ' },
    career: { en: 'Leadership feels hollow; transition to dharmic work', si: 'නායකත්වය හිස් ලෙස දැනේ; ධාර්මික කටයුතු වෙත මාරු වීමක්' },
    relationships: { en: 'Father karma; authority figures become spiritual mirrors', si: 'පියා හා බැඳුණු කර්මය; බලධාරීන් අධ්‍යාත්මික කැඩපත් බවට පත් වේ' },
    ratingMod: -1,
  },

  // ─── Moon combinations ───────────────────────────────────────────────────
  'Moon-Moon': {
    theme: { en: 'Double Chandra — peak of emotional intelligence and public connection', si: 'ද්විගුණ චන්ද්‍ර — හැඟීම් තේරුම් ගැනීමේ හැකියාව හා මහජන සම්බන්ධතාවල උච්චතම අවස්ථාව' },
    health: { en: 'Mental and emotional health excellent; stay hydrated', si: 'මානසික හා හැඟීම්බර සෞඛ්‍යය විශිෂ්ටයි; ප්‍රමාණවත් ජලය පානය කරන්න' },
    wealth: { en: 'Public business, real estate, hospitality all thrive', si: 'මහජන ව්‍යාපාර, දේපළ හා ආගන්තුක සත්කාරය සමෘද්ධිමත් වේ' },
    career: { en: 'Public roles, emotional intelligence leadership', si: 'මහජන තනතුරු හා හැඟීම් තේරුම් ගන්නා නායකත්වය' },
    relationships: { en: 'Deep family bonds; women bring luck and support', si: 'ගැඹුරු පවුල් බැඳීම්; කාන්තාවන් වාසනාව හා සහය ගෙන එයි' },
    bonus: { en: 'Excellent for public communication and emotional creativity', si: 'මහජන සන්නිවේදනයට හා හැඟීම්බර නිර්මාණශීලීත්වයට විශිෂ්ටයි' },
    ratingMod: 1,
  },
  'Moon-Sun': {
    theme: { en: 'Chandra-Surya — public authority and balanced energy', si: 'චන්ද්‍ර-සූර්ය — මහජන බලය හා සමතුලිත ශක්තිය' },
    health: { en: 'Good vitality; emotional and physical balance needed', si: 'ජීවශක්තිය හොඳයි; හැඟීම්බර හා ශාරීරික සමතුලිතතාව අවශ්‍යය' },
    wealth: { en: 'Public recognition brings financial rewards', si: 'මහජන පිළිගැනීම මූල්‍ය ප්‍රතිලාභ ගෙන දෙයි' },
    career: { en: 'Leadership in public domain; government and public service', si: 'මහජන ක්ෂේත්‍රයේ නායකත්වය; රාජ්‍ය හා මහජන සේවය' },
    relationships: { en: 'Family harmony; public image matters in relationships', si: 'පවුලේ සමගිය; සම්බන්ධතාවලදී මහජන ප්‍රතිරූපය වැදගත් වේ' },
    ratingMod: 1,
  },
  'Moon-Mars': {
    theme: { en: 'Chandra-Mangal — emotional courage and protective instinct', si: 'චන්ද්‍ර-කුජ — හැඟීම්බර ධෛර්යය හා ආරක්ෂා කිරීමේ නැඹුරුව' },
    health: { en: 'Blood and hormonal balance needs attention', si: 'රුධිර හා හෝමෝන සමතුලිතතාව ගැන අවධානය අවශ්‍යය' },
    wealth: { en: 'Property, real estate, and public business income', si: 'දේපළ, ඉඩම් හා මහජන ව්‍යාපාර ආදායම්' },
    career: { en: 'Physical and public roles; nursing, military, real estate', si: 'ශාරීරික හා මහජන කටයුතු; හෙද සේවය, හමුදාව හා දේපළ වෙළඳාම' },
    relationships: { en: 'Protective and passionate; mother-sibling dynamics', si: 'ආරක්ෂාකාරී හා ආශාවෙන් පිරි; මව හා සහෝදරයන් සමඟ සම්බන්ධතා' },
    ratingMod: 0,
  },
  'Moon-Rahu': {
    theme: { en: 'Chandra-Rahu — emotional turbulence and psychic intensity', si: 'චන්ද්‍ර-රාහු — හැඟීම්බර කැළඹීම හා අභ්‍යන්තර තීව්‍රතාව' },
    health: { en: 'Mental health, anxiety, and psychosomatic issues', si: 'මානසික සෞඛ්‍යය, කනස්සල්ල හා මනස නිසා ඇති වන ශාරීරික ගැටලු' },
    wealth: { en: 'Emotional financial decisions can backfire', si: 'හැඟීම් මත ගන්නා මූල්‍ය තීරණ අහිතකර විය හැක' },
    career: { en: 'Media, public platforms with instability', si: 'මාධ්‍ය හා මහජන වේදිකා, නමුත් අස්ථිරතාවක් සහිතව' },
    relationships: { en: 'Obsessive emotional bonds; mother complications', si: 'ඇලී ගැලී යන හැඟීම්බර බැඳීම්; මව සමඟ සංකීර්ණතා' },
    warning: { en: 'Guard against anxiety, emotional manipulation and delusions', si: 'කනස්සල්ල, හැඟීම් හසුරුවීම හා මිථ්‍යා විශ්වාසවලින් ආරක්ෂා වන්න' },
    ratingMod: -1,
  },
  'Moon-Jupiter': {
    theme: { en: 'Chandra-Guru — Gajakesari yoga energy; wisdom and fame', si: 'චන්ද්‍ර-ගුරු — ගජකේසරී යෝග ශක්තිය; ඥානය හා කීර්තිය' },
    health: { en: 'Strong overall; emotional wisdom supports healing', si: 'සමස්තයක් ලෙස ප්‍රබලයි; හැඟීම්බර ඥානය සුවවීමට උපකාරී වේ' },
    wealth: { en: 'Public wealth expansion; advisory and public income', si: 'මහජනතාව හරහා ධන ව්‍යාප්තිය; උපදේශන හා මහජන ආදායම්' },
    career: { en: 'Public teaching, emotional leadership, advisory roles', si: 'මහජන ඉගැන්වීම, හැඟීම් තේරුම් ගන්නා නායකත්වය හා උපදේශන කටයුතු' },
    relationships: { en: 'Family blessed; children bring joy; wise relationships', si: 'පවුල ආශිර්වාද ලබයි; දරුවන් සතුට ගෙන එයි; ඥානවන්ත සම්බන්ධතා' },
    bonus: { en: 'Gajakesari energy — fame, wealth and public recognition', si: 'ගජකේසරී ශක්තිය — කීර්තිය, ධනය හා මහජන පිළිගැනීම' },
    ratingMod: 2,
  },
  'Moon-Saturn': {
    theme: { en: 'Chandra-Shani — emotional discipline; Vish Yoga influence', si: 'චන්ද්‍ර-ශනි — හැඟීම් පිළිබඳ විනය; විෂ යෝගයේ බලපෑම' },
    health: { en: 'Depression, anxiety, and emotional suppression risk', si: 'අවපීඩනය, කනස්සල්ල හා හැඟීම් යටපත් වීමේ අවදානම' },
    wealth: { en: 'Hard emotional labor for slow financial gains', si: 'මන්දගාමී මූල්‍ය ලාභ සඳහා දැඩි හැඟීම්බර වෙහෙසක්' },
    career: { en: 'Emotionally demanding work; service and care roles', si: 'හැඟීම්බර වශයෙන් වෙහෙසකර වැඩ; සේවා හා රැකවරණ කටයුතු' },
    relationships: { en: 'Emotional distance; duty over desire in relationships', si: 'හැඟීම්බර දුරස්ථභාවය; සම්බන්ධතාවල ආශාවට වඩා යුතුකම ඉස්මතු වේ' },
    warning: { en: 'Vish Yoga influence — emotional health requires active care', si: 'විෂ යෝගයේ බලපෑම — හැඟීම්බර සෞඛ්‍යයට ක්‍රියාශීලී අවධානයක් අවශ්‍යය' },
    ratingMod: -1,
  },
  'Moon-Mercury': {
    theme: { en: 'Chandra-Budha — emotional intelligence and communication', si: 'චන්ද්‍ර-බුධ — හැඟීම් තේරුම් ගැනීමේ හැකියාව හා සන්නිවේදනය' },
    health: { en: 'Nervous system and digestive health balance', si: 'ස්නායු පද්ධතිය හා ජීර්ණ සෞඛ්‍යය සමතුලිතව තබා ගන්න' },
    wealth: { en: 'Communication, writing, and public business income', si: 'සන්නිවේදන, ලේඛන හා මහජන ව්‍යාපාර ආදායම්' },
    career: { en: 'Writing, media, counseling, public communication', si: 'ලේඛන, මාධ්‍ය, උපදේශනය හා මහජන සන්නිවේදනය' },
    relationships: { en: 'Communicative and adaptable; variety in social connections', si: 'සන්නිවේදනශීලී හා හැඩ ගැසෙන සුළු; සමාජ සම්බන්ධතාවල විවිධත්වය' },
    ratingMod: 1,
  },
  'Moon-Venus': {
    theme: { en: 'Chandra-Shukra — emotional beauty and romantic sensitivity', si: 'චන්ද්‍ර-ශුක්‍ර — හැඟීම්බර සුන්දරත්වය හා ප්‍රේම සංවේදිතාව' },
    health: { en: 'Reproductive and kidney health attention needed', si: 'ප්‍රජනන හා වකුගඩු සෞඛ්‍යය ගැන අවධානය අවශ්‍යය' },
    wealth: { en: 'Arts, beauty, hospitality, and public-facing income', si: 'කලා, රූපලාවණ්‍ය, ආගන්තුක සත්කාරය හා මහජනතාව ආශ්‍රිත ආදායම්' },
    career: { en: 'Entertainment, arts, emotional sales and hospitality', si: 'විනෝදාස්වාදය, කලා, හැඟීම් ආශ්‍රිත අලෙවිය හා ආගන්තුක සත්කාරය' },
    relationships: { en: 'Romantic and nurturing bonds; spouse/partner brings comfort', si: 'ප්‍රේමනීය හා රැකබලා ගන්නා බැඳීම්; කලත්‍රයා සැනසීම ගෙන එයි' },
    bonus: { en: 'Very favorable for love, creativity and feminine energy', si: 'ආදරයට, නිර්මාණශීලීත්වයට හා ස්ත්‍රී ශක්තියට ඉතා හිතකරය' },
    ratingMod: 1,
  },
  'Moon-Ketu': {
    theme: { en: 'Chandra-Ketu — emotional detachment and spiritual sensitivity', si: 'චන්ද්‍ර-කේතු — හැඟීම්බර වෙන් වීම හා අධ්‍යාත්මික සංවේදිතාව' },
    health: { en: 'Mental health and mysterious emotional conditions', si: 'මානසික සෞඛ්‍යය හා හඳුනාගත නොහැකි හැඟීම්බර තත්ත්ව' },
    wealth: { en: 'Detachment from wealth; spiritual income', si: 'ධනයෙන් වෙන් වීම; අධ්‍යාත්මික ආදායම්' },
    career: { en: 'Healing, research, spiritual counseling', si: 'සුවකිරීම, පර්යේෂණ හා අධ්‍යාත්මික උපදේශනය' },
    relationships: { en: 'Emotional distance; past-life bonds surface', si: 'හැඟීම්බර දුරස්ථභාවය; පෙර භවවල බැඳීම් මතු වේ' },
    warning: { en: 'Guard against depression and emotional withdrawal', si: 'අවපීඩනයෙන් හා හැඟීම්බර වශයෙන් ඉවත් වීමෙන් ආරක්ෂා වන්න' },
    ratingMod: -1,
  },

  // ─── Mars combinations ───────────────────────────────────────────────────
  'Mars-Mars': {
    theme: { en: 'Double Mangal — explosive energy, courage and property focus', si: 'ද්විගුණ කුජ — පුපුරන සුළු ශක්තිය, ධෛර්යය හා දේපළ කෙරෙහි අවධානය' },
    health: { en: 'Accidents, fever, blood disorders — physical caution', si: 'අනතුරු, උණ හා රුධිර ආබාධ — ශාරීරික ප්‍රවේශම අවශ්‍යය' },
    wealth: { en: 'Property, technical business, bold investments', si: 'දේපළ, තාක්ෂණික ව්‍යාපාර හා නිර්භීත ආයෝජන' },
    career: { en: 'Military, engineering, sports, real estate at peak', si: 'හමුදා සේවය, ඉංජිනේරු විද්‍යාව, ක්‍රීඩා හා දේපළ වෙළඳාම උච්චතම මට්ටමේ' },
    relationships: { en: 'Passionate but volatile; sibling matters important', si: 'ආශාවෙන් පිරි නමුත් අස්ථිර; සහෝදර කටයුතු වැදගත් වේ' },
    warning: { en: 'Double Mars energy — control aggression and impulsiveness', si: 'ද්විගුණ කුජ ශක්තිය — ආක්‍රමණශීලීත්වය හා හදිසිකම පාලනය කර ගන්න' },
    ratingMod: 0,
  },
  'Mars-Sun': {
    theme: { en: 'Mangal-Surya — bold authority and physical leadership', si: 'කුජ-සූර්ය — නිර්භීත බලය හා ශාරීරික නායකත්වය' },
    health: { en: 'High energy; blood pressure and heat risk', si: 'ශක්තිය ඉහළය; රුධිර පීඩනය හා ශරීර උණුසුම පිළිබඳ අවදානම' },
    wealth: { en: 'Government and technical income; property gains', si: 'රාජ්‍ය හා තාක්ෂණික ආදායම්; දේපළ ලාභ' },
    career: { en: 'Military leadership, government, sports, engineering', si: 'හමුදා නායකත්වය, රාජ්‍ය සේවය, ක්‍රීඩා හා ඉංජිනේරු විද්‍යාව' },
    relationships: { en: 'Assertive with father; competitive with authority', si: 'පියා සමඟ ස්ථිර ලෙස කටයුතු කිරීම; බලධාරීන් සමඟ තරඟකාරිත්වය' },
    ratingMod: 1,
  },
  'Mars-Moon': {
    theme: { en: 'Mangal-Chandra — emotional courage and protective strength', si: 'කුජ-චන්ද්‍ර — හැඟීම්බර ධෛර්යය හා ආරක්ෂාකාරී ශක්තිය' },
    health: { en: 'Blood, hormonal, and emotional health balance', si: 'රුධිර, හෝමෝන හා හැඟීම්බර සෞඛ්‍යය සමතුලිතව තබා ගන්න' },
    wealth: { en: 'Property and public business; emotional financial decisions', si: 'දේපළ හා මහජන ව්‍යාපාර; හැඟීම් මත ගන්නා මූල්‍ය තීරණ' },
    career: { en: 'Physical and public roles; defense, real estate, nursing', si: 'ශාරීරික හා මහජන කටයුතු; ආරක්ෂක සේවය, දේපළ වෙළඳාම හා හෙද සේවය' },
    relationships: { en: 'Protective intensity; emotional volatility in relationships', si: 'ආරක්ෂා කිරීමේ තීව්‍රතාව; සම්බන්ධතාවල හැඟීම්බර අස්ථිරතාව' },
    ratingMod: 0,
  },
  'Mars-Mercury': {
    theme: { en: 'Mangal-Budha — technical communication and sharp analysis', si: 'කුජ-බුධ — තාක්ෂණික සන්නිවේදනය හා තියුණු විශ්ලේෂණය' },
    health: { en: 'Nervous system and blood health balance', si: 'ස්නායු පද්ධතිය හා රුධිර සෞඛ්‍යය සමතුලිතව තබා ගන්න' },
    wealth: { en: 'Technical business, trading, and engineering income', si: 'තාක්ෂණික ව්‍යාපාර, වෙළඳාම හා ඉංජිනේරු ආදායම්' },
    career: { en: 'Technical writing, engineering, trading, IT', si: 'තාක්ෂණික ලේඛන, ඉංජිනේරු විද්‍යාව, වෙළඳාම හා තොරතුරු තාක්ෂණය' },
    relationships: { en: 'Witty and quick; intellectual friendships', si: 'චතුර හා ක්ෂණික; බුද්ධිමය මිත්‍රත්ව' },
    ratingMod: 1,
  },
  'Mars-Jupiter': {
    theme: { en: 'Mangal-Guru — righteous courage and expansive action', si: 'කුජ-ගුරු — ධාර්මික ධෛර්යය හා පුළුල් ක්‍රියාව' },
    health: { en: 'Energy well-supported; liver and weight care', si: 'ශක්තිය හොඳින් රැකෙයි; අක්මාව හා ශරීර බර ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Legal income, property, and business expansion', si: 'නීතිමය ආදායම්, දේපළ හා ව්‍යාපාර ව්‍යාප්තිය' },
    career: { en: 'Law, military leadership, entrepreneurship, sports', si: 'නීතිය, හමුදා නායකත්වය, ව්‍යවසායකත්වය හා ක්‍රීඩා' },
    relationships: { en: 'Courageous relationships; mentor-student bonds', si: 'ධෛර්ය සම්පන්න සම්බන්ධතා; ගුරු-ශිෂ්‍ය බැඳීම්' },
    ratingMod: 1,
  },
  'Mars-Venus': {
    theme: { en: 'Mangal-Shukra — passionate creativity and property-luxury balance', si: 'කුජ-ශුක්‍ර — ආශාවෙන් පිරි නිර්මාණශීලීත්වය හා දේපළ-සුඛෝපභෝග සමතුලිතතාව' },
    health: { en: 'Sexual health and energy management important', si: 'ලිංගික සෞඛ්‍යය හා ශක්ති කළමනාකරණය වැදගත් වේ' },
    wealth: { en: 'Property, arts, luxury, and entertainment income', si: 'දේපළ, කලා, සුඛෝපභෝගී භාණ්ඩ හා විනෝදාස්වාද ආදායම්' },
    career: { en: 'Real estate, arts, hospitality, entertainment', si: 'දේපළ වෙළඳාම, කලා, ආගන්තුක සත්කාරය හා විනෝදාස්වාදය' },
    relationships: { en: 'Intensely passionate romance; attraction is strong', si: 'තීව්‍ර ලෙස ආශාවෙන් පිරි ප්‍රේමය; ආකර්ෂණය ප්‍රබලයි' },
    ratingMod: 1,
  },
  'Mars-Saturn': {
    theme: { en: 'Mangal-Shani — effort versus obstacle; discipline through hardship', si: 'කුජ-ශනි — උත්සාහය හා බාධාව අතර ගැටුම; දුෂ්කරතා හරහා විනය' },
    health: { en: 'Chronic fatigue, injuries, and inflammation risk', si: 'නිදන්ගත වෙහෙස, තුවාල හා දැවිලි තත්ත්ව ඇතිවීමේ අවදානම' },
    wealth: { en: 'Hard work with limited returns initially', si: 'මුලදී වෙහෙස මහන්සියට සීමිත ප්‍රතිලාභයක්' },
    career: { en: 'Engineering, labor, and physical service under pressure', si: 'පීඩනය යටතේ ඉංජිනේරු, ශ්‍රම හා ශාරීරික සේවා කටයුතු' },
    relationships: { en: 'Strained relationships with siblings and authority figures', si: 'සහෝදරයන් හා බලධාරීන් සමඟ ආතතියෙන් යුත් සම්බන්ධතා' },
    warning: { en: 'Patience is critical — aggression against obstacles will backfire', si: 'ඉවසීම අත්‍යවශ්‍යය — බාධකවලට එරෙහිව බලහත්කාරය අහිතකර වේ' },
    ratingMod: -1,
  },
  'Mars-Rahu': {
    theme: { en: 'Mangal-Rahu — explosive and reckless energy; accidents risk', si: 'කුජ-රාහු — පුපුරන සුළු, නොසැලකිලිමත් ශක්තිය; අනතුරු අවදානම' },
    health: { en: 'Accidents, infections, and impulsive health choices', si: 'අනතුරු, ආසාදන හා හදිසියේ ගන්නා සෞඛ්‍ය තීරණ' },
    wealth: { en: 'High-risk ventures with unpredictable outcomes', si: 'ප්‍රතිඵල අනපේක්ෂිත අධි අවදානම් ව්‍යාපෘති' },
    career: { en: 'Aggressive career moves; sudden rise or fall', si: 'ආක්‍රමණශීලී වෘත්තීය තීරණ; හදිසි නැගීමක් හෝ වැටීමක්' },
    relationships: { en: 'Volatile, passionate but unstable relationships', si: 'කැළඹිලි සහගත, ආශාවෙන් පිරි නමුත් අස්ථිර සම්බන්ධතා' },
    warning: { en: 'Most accident-prone combination — extreme physical caution needed', si: 'අනතුරු වඩාත්ම ඇති විය හැකි එකතුව — දැඩි ශාරීරික ප්‍රවේශමක් අවශ්‍යය' },
    ratingMod: -1,
  },
  'Mars-Ketu': {
    theme: { en: 'Mangal-Ketu — past karma with siblings and property; accident risk', si: 'කුජ-කේතු — සහෝදරයන් හා දේපළ හා බැඳුණු පෙර කර්මය; අනතුරු අවදානම' },
    health: { en: 'Surgeries, wounds, mysterious fevers', si: 'සැත්කම්, තුවාල හා හඳුනාගත නොහැකි උණ' },
    wealth: { en: 'Property disputes and sudden material losses', si: 'දේපළ ආරවුල් හා හදිසි භෞතික පාඩු' },
    career: { en: 'Technical and investigative work; forced career changes', si: 'තාක්ෂණික හා විමර්ශන කටයුතු; බලෙන් සිදු වන වෘත්තීය වෙනස්කම්' },
    relationships: { en: 'Sibling karma surfaces; competitive past-life dynamics', si: 'සහෝදර කර්මය මතු වේ; පෙර භවයේ තරඟකාරී සම්බන්ධතා' },
    warning: { en: 'Physical accidents more likely — take precautions seriously', si: 'ශාරීරික අනතුරු සිදු වීමේ ඉඩ වැඩිය — ආරක්ෂක පියවර බැරෑරුම්ව ගන්න' },
    ratingMod: -1,
  },

  // ─── Mercury combinations ────────────────────────────────────────────────
  'Mercury-Mercury': {
    theme: { en: 'Double Budha — peak of intelligence, communication and commerce', si: 'ද්විගුණ බුධ — බුද්ධිය, සන්නිවේදනය හා වාණිජ කටයුතුවල උච්චතම අවස්ථාව' },
    health: { en: 'Nervous system care critical; avoid mental overload', si: 'ස්නායු පද්ධතියේ සත්කාරය අත්‍යවශ්‍යය; මානසික බර වළක්වන්න' },
    wealth: { en: 'Business, trading, writing, and IT income maximized', si: 'ව්‍යාපාර, වෙළඳාම, ලේඛන හා තොරතුරු තාක්ෂණ ආදායම් උපරිම වේ' },
    career: { en: 'All Mercury fields — communication, trade, IT — at peak', si: 'බුධට අයත් සියලු ක්ෂේත්‍ර — සන්නිවේදනය, වෙළඳාම හා තොරතුරු තාක්ෂණය — උච්චතම මට්ටමේ' },
    relationships: { en: 'Witty social connections; intellectual partnerships', si: 'චතුර සමාජ සම්බන්ධතා; බුද්ධිමය හවුල්කාරිත්ව' },
    bonus: { en: 'Excellent for business, education, and publishing launches', si: 'ව්‍යාපාර, අධ්‍යාපන හා ප්‍රකාශන ආරම්භ කිරීමට විශිෂ්ටයි' },
    ratingMod: 2,
  },
  'Mercury-Sun': {
    theme: { en: 'Budha-Surya — Budhaditya yoga continuation; leadership through intellect', si: 'බුධ-සූර්ය — බුධාදිත්‍ය යෝගය දිගටම; බුද්ධිය හරහා නායකත්වය' },
    health: { en: 'Eye health and nervous energy balance', si: 'ඇස්වල සෞඛ්‍යය හා ස්නායු ශක්තිය සමතුලිතව තබා ගන්න' },
    wealth: { en: 'Government communication, writing income, advisory', si: 'රාජ්‍ය සන්නිවේදනය, ලේඛන ආදායම් හා උපදේශනය' },
    career: { en: 'Government writing, media, analytical leadership', si: 'රාජ්‍ය ලේඛන කටයුතු, මාධ්‍ය හා විශ්ලේෂණාත්මක නායකත්වය' },
    relationships: { en: 'Intellectual authority; positive with younger people', si: 'බුද්ධිමය බලය; තරුණ පිරිස සමඟ හිතකර සම්බන්ධතා' },
    ratingMod: 1,
  },
  'Mercury-Moon': {
    theme: { en: 'Budha-Chandra — emotional intelligence and public communication', si: 'බුධ-චන්ද්‍ර — හැඟීම් තේරුම් ගැනීමේ හැකියාව හා මහජන සන්නිවේදනය' },
    health: { en: 'Nervous and digestive health attention', si: 'ස්නායු හා ජීර්ණ සෞඛ්‍යය ගැන අවධානය යොමු කරන්න' },
    wealth: { en: 'Public communication, writing, and trade income', si: 'මහජන සන්නිවේදනය, ලේඛන හා වෙළඳ ආදායම්' },
    career: { en: 'Media, public writing, counseling, hospitality', si: 'මාධ්‍ය, මහජන ලේඛන, උපදේශනය හා ආගන්තුක සත්කාරය' },
    relationships: { en: 'Communicative and emotionally responsive connections', si: 'සන්නිවේදනශීලී හා හැඟීම්වලට ප්‍රතිචාර දක්වන සම්බන්ධතා' },
    ratingMod: 1,
  },
  'Mercury-Mars': {
    theme: { en: 'Budha-Mangal — sharp technical mind and decisive action', si: 'බුධ-කුජ — තියුණු තාක්ෂණික මනස හා තීරණාත්මක ක්‍රියාව' },
    health: { en: 'Nervous and blood health balance', si: 'ස්නායු හා රුධිර සෞඛ්‍යය සමතුලිතව තබා ගන්න' },
    wealth: { en: 'Technical business, trading, and engineering income', si: 'තාක්ෂණික ව්‍යාපාර, වෙළඳාම හා ඉංජිනේරු ආදායම්' },
    career: { en: 'Technical communication, engineering, IT', si: 'තාක්ෂණික සන්නිවේදනය, ඉංජිනේරු විද්‍යාව හා තොරතුරු තාක්ෂණය' },
    relationships: { en: 'Decisive and direct; brief but stimulating connections', si: 'තීරණාත්මක හා ඍජු; කෙටි නමුත් උත්තේජනකාරී සම්බන්ධතා' },
    ratingMod: 1,
  },
  'Mercury-Jupiter': {
    theme: { en: 'Budha-Guru — intellectual wisdom and business prosperity', si: 'බුධ-ගුරු — බුද්ධිමය ඥානය හා ව්‍යාපාරික සමෘද්ධිය' },
    health: { en: 'Liver and nervous system balance needed', si: 'අක්මාව හා ස්නායු පද්ධතිය සමතුලිතව තබා ගත යුතුය' },
    wealth: { en: 'Major income from consulting, teaching, and business', si: 'උපදේශනය, ඉගැන්වීම හා ව්‍යාපාරවලින් විශාල ආදායමක්' },
    career: { en: 'Finance, law, education, and advisory roles', si: 'මූල්‍ය සේවා, නීතිය, අධ්‍යාපනය හා උපදේශන කටයුතු' },
    relationships: { en: 'Wise and generous relationships; mentor connections', si: 'ඥානවන්ත හා නොමසුරු සම්බන්ධතා; මඟපෙන්වන්නන් සමඟ බැඳීම්' },
    bonus: { en: 'Exceptional for business expansion and educational achievements', si: 'ව්‍යාපාර ව්‍යාප්තියට හා අධ්‍යාපන ජයග්‍රහණවලට අසාමාන්‍ය ලෙස හිතකරය' },
    ratingMod: 2,
  },
  'Mercury-Venus': {
    theme: { en: 'Budha-Shukra — creative intelligence and artistic commerce', si: 'බුධ-ශුක්‍ර — නිර්මාණශීලී බුද්ධිය හා කලාත්මක වාණිජ කටයුතු' },
    health: { en: 'Reproductive and nervous health care', si: 'ප්‍රජනන හා ස්නායු සෞඛ්‍යය ගැන සැලකිලිමත් වන්න' },
    wealth: { en: 'Arts business, beauty, fashion, and digital income', si: 'කලා ව්‍යාපාර, රූපලාවණ්‍ය, විලාසිතා හා ඩිජිටල් ආදායම්' },
    career: { en: 'Creative industries, digital media, fashion, beauty', si: 'නිර්මාණශීලී කර්මාන්ත, ඩිජිටල් මාධ්‍ය, විලාසිතා හා රූපලාවණ්‍ය' },
    relationships: { en: 'Charming and communicative romantic connections', si: 'ආකර්ෂණීය හා සන්නිවේදනශීලී ප්‍රේම සම්බන්ධතා' },
    ratingMod: 2,
  },
  'Mercury-Saturn': {
    theme: { en: 'Budha-Shani — methodical planning and systematic discipline', si: 'බුධ-ශනි — ක්‍රමවත් සැලසුම්කරණය හා විධිමත් විනය' },
    health: { en: 'Nervous and joint health care important', si: 'ස්නායු හා සන්ධි සෞඛ්‍යය ගැන සැලකිලිමත් වීම වැදගත් වේ' },
    wealth: { en: 'Slow methodical income; long-term business planning', si: 'මන්දගාමී, ක්‍රමවත් ආදායමක්; දිගු කාලීන ව්‍යාපාර සැලසුම්' },
    career: { en: 'Detail-oriented, systematic work and administration', si: 'සියුම් විස්තර සමඟ කරන ක්‍රමවත් වැඩ හා පරිපාලනය' },
    relationships: { en: 'Intellectual but emotionally reserved connections', si: 'බුද්ධිමය නමුත් හැඟීම් ප්‍රකාශ නොකරන සම්බන්ධතා' },
    ratingMod: 0,
  },
  'Mercury-Rahu': {
    theme: { en: 'Budha-Rahu — innovative thinking and unconventional communication', si: 'බුධ-රාහු — නවෝත්පාදන චින්තනය හා සම්ප්‍රදායික නොවන සන්නිවේදනය' },
    health: { en: 'Nervous anxiety and respiratory health attention', si: 'ස්නායු කනස්සල්ල හා ශ්වසන සෞඛ්‍යය ගැන අවධානය' },
    wealth: { en: 'Technology, foreign trade, digital and unconventional income', si: 'තාක්ෂණය, විදේශ වෙළඳාම, ඩිජිටල් හා සම්ප්‍රදායික නොවන ආදායම්' },
    career: { en: 'Technology innovation, foreign communication, digital entrepreneurship', si: 'තාක්ෂණික නවෝත්පාදන, විදේශ සන්නිවේදනය හා ඩිජිටල් ව්‍යවසායකත්වය' },
    relationships: { en: 'Unusual and intellectually stimulating connections', si: 'අසාමාන්‍ය හා බුද්ධිමය වශයෙන් උත්තේජනකාරී සම්බන්ධතා' },
    ratingMod: 0,
  },
  'Mercury-Ketu': {
    theme: { en: 'Budha-Ketu — intuitive research and spiritual communication', si: 'බුධ-කේතු — ඉවෙන් කරන පර්යේෂණ හා අධ්‍යාත්මික සන්නිවේදනය' },
    health: { en: 'Nervous system and mysterious health sensitivity', si: 'ස්නායු පද්ධතිය හා හඳුනාගත නොහැකි සෞඛ්‍ය සංවේදිතාව' },
    wealth: { en: 'Research, writing, and spiritual communication income', si: 'පර්යේෂණ, ලේඛන හා අධ්‍යාත්මික සන්නිවේදන ආදායම්' },
    career: { en: 'Research, investigation, spiritual writing and education', si: 'පර්යේෂණ, විමර්ශන, අධ්‍යාත්මික ලේඛන හා අධ්‍යාපනය' },
    relationships: { en: 'Intuitive but detached intellectual connections', si: 'ඉවෙන් තේරුම් ගන්නා නමුත් නොඇලෙන බුද්ධිමය සම්බන්ධතා' },
    ratingMod: 0,
  },
};
