/**
 * GENERATED by backtest/writeEvidence.ts from the 550-lives backtest — do not edit
 * by hand; rerun the script (see backtest/README.md) when a rule or score changes.
 *
 * INDICATOR_EVIDENCE: for each classical indicator (classicalIndicators.ts), the
 * share of real dated events it was present at versus the share of the same
 * people's nearby days (±4 years) — lift = the ratio, lo/hi its 95% interval,
 * z the standard score of the difference (the app calls a difference "clear"
 * only at |z| >= 3, because ~36 indicators are shown side by side).
 * SCORE_EVIDENCE: where the engine's own area score sat at those events among
 * the person's nearby periods (0.5 = what chance gives).
 */
export const EVIDENCE_META = {"people":544,"events":{"A":1300,"M":391,"U":226},"generated":"2026-10-08"} as const;

export interface IndicatorEvidence { n: number; eventShare: number; baseShare: number; lift: number; lo: number; hi: number; z: number }
export const INDICATOR_EVIDENCE: Record<string, IndicatorEvidence> = {
 "A|A MD connected H": {
  "n": 1300,
  "eventShare": 0.433,
  "baseShare": 0.428,
  "lift": 1.011,
  "lo": 0.992,
  "hi": 1.031,
  "z": 0.82
 },
 "A|A AD connected H": {
  "n": 1300,
  "eventShare": 0.415,
  "baseShare": 0.409,
  "lift": 1.015,
  "lo": 0.961,
  "hi": 1.072,
  "z": 0.53
 },
 "A|A MD|AD Jaimini AmK": {
  "n": 1300,
  "eventShare": 0.209,
  "baseShare": 0.201,
  "lift": 1.041,
  "lo": 0.964,
  "hi": 1.127,
  "z": 0.96
 },
 "A|A MD|AD natural karaka": {
  "n": 1300,
  "eventShare": 0.365,
  "baseShare": 0.373,
  "lift": 0.978,
  "lo": 0.921,
  "hi": 1.036,
  "z": -0.74
 },
 "A|A Jup on H": {
  "n": 1300,
  "eventShare": 0.352,
  "baseShare": 0.333,
  "lift": 1.056,
  "lo": 0.983,
  "hi": 1.141,
  "z": 1.44
 },
 "A|A Sat on H": {
  "n": 1300,
  "eventShare": 0.346,
  "baseShare": 0.334,
  "lift": 1.035,
  "lo": 0.955,
  "hi": 1.109,
  "z": 0.93
 },
 "A|A double transit H": {
  "n": 1300,
  "eventShare": 0.117,
  "baseShare": 0.114,
  "lift": 1.028,
  "lo": 0.881,
  "hi": 1.18,
  "z": 0.37
 },
 "A|A convergence >= 5": {
  "n": 1300,
  "eventShare": 0.302,
  "baseShare": 0.296,
  "lift": 1.02,
  "lo": 0.94,
  "hi": 1.094,
  "z": 0.53
 },
 "M|M MD connected H": {
  "n": 391,
  "eventShare": 0.353,
  "baseShare": 0.354,
  "lift": 0.997,
  "lo": 0.955,
  "hi": 1.038,
  "z": -0.1
 },
 "M|M AD connected H": {
  "n": 391,
  "eventShare": 0.368,
  "baseShare": 0.381,
  "lift": 0.966,
  "lo": 0.859,
  "hi": 1.072,
  "z": -0.61
 },
 "M|M MD|AD Jaimini DK": {
  "n": 391,
  "eventShare": 0.217,
  "baseShare": 0.209,
  "lift": 1.043,
  "lo": 0.905,
  "hi": 1.188,
  "z": 0.57
 },
 "M|M MD|AD natural karaka": {
  "n": 391,
  "eventShare": 0.289,
  "baseShare": 0.291,
  "lift": 0.992,
  "lo": 0.879,
  "hi": 1.114,
  "z": -0.14
 },
 "M|M Jup on H": {
  "n": 391,
  "eventShare": 0.345,
  "baseShare": 0.334,
  "lift": 1.034,
  "lo": 0.898,
  "hi": 1.17,
  "z": 0.48
 },
 "M|M Sat on H": {
  "n": 391,
  "eventShare": 0.355,
  "baseShare": 0.326,
  "lift": 1.092,
  "lo": 0.951,
  "hi": 1.251,
  "z": 1.29
 },
 "M|M double transit H": {
  "n": 391,
  "eventShare": 0.118,
  "baseShare": 0.113,
  "lift": 1.041,
  "lo": 0.786,
  "hi": 1.301,
  "z": 0.3
 },
 "M|M nodes on H axis": {
  "n": 391,
  "eventShare": 0.159,
  "baseShare": 0.167,
  "lift": 0.952,
  "lo": 0.748,
  "hi": 1.145,
  "z": -0.43
 },
 "M|M convergence >= 5": {
  "n": 391,
  "eventShare": 0.223,
  "baseShare": 0.248,
  "lift": 0.898,
  "lo": 0.752,
  "hi": 1.043,
  "z": -1.28
 },
 "U|U MD connected H": {
  "n": 226,
  "eventShare": 0.327,
  "baseShare": 0.352,
  "lift": 0.929,
  "lo": 0.867,
  "hi": 0.983,
  "z": -1.88
 },
 "U|U AD connected H": {
  "n": 226,
  "eventShare": 0.429,
  "baseShare": 0.417,
  "lift": 1.03,
  "lo": 0.899,
  "hi": 1.163,
  "z": 0.44
 },
 "U|U Sat on H": {
  "n": 226,
  "eventShare": 0.327,
  "baseShare": 0.342,
  "lift": 0.957,
  "lo": 0.773,
  "hi": 1.145,
  "z": -0.48
 },
 "U|* Sade Sati rising": {
  "n": 226,
  "eventShare": 0.088,
  "baseShare": 0.098,
  "lift": 0.905,
  "lo": 0.583,
  "hi": 1.252,
  "z": -0.53
 },
 "U|* Sade Sati peak": {
  "n": 226,
  "eventShare": 0.111,
  "baseShare": 0.087,
  "lift": 1.271,
  "lo": 0.877,
  "hi": 1.67,
  "z": 1.44
 },
 "U|* Sade Sati setting": {
  "n": 226,
  "eventShare": 0.071,
  "baseShare": 0.077,
  "lift": 0.918,
  "lo": 0.567,
  "hi": 1.29,
  "z": -0.41
 },
 "U|* Ashtama Shani": {
  "n": 226,
  "eventShare": 0.058,
  "baseShare": 0.072,
  "lift": 0.795,
  "lo": 0.402,
  "hi": 1.194,
  "z": -0.97
 },
 "U|* Kantaka Shani": {
  "n": 226,
  "eventShare": 0.199,
  "baseShare": 0.249,
  "lift": 0.8,
  "lo": 0.605,
  "hi": 1.011,
  "z": -1.84
 },
 "U|U convergence >= 5": {
  "n": 226,
  "eventShare": 0.296,
  "baseShare": 0.302,
  "lift": 0.983,
  "lo": 0.798,
  "hi": 1.161,
  "z": -0.18
 },
 "A|* AD in dhana yoga": {
  "n": 1300,
  "eventShare": 0.334,
  "baseShare": 0.328,
  "lift": 1.018,
  "lo": 0.951,
  "hi": 1.089,
  "z": 0.51
 },
 "A|* Jup good from Moon": {
  "n": 1300,
  "eventShare": 0.406,
  "baseShare": 0.416,
  "lift": 0.976,
  "lo": 0.91,
  "hi": 1.031,
  "z": -0.74
 },
 "A|* Jup sign SAV >= 30": {
  "n": 1300,
  "eventShare": 0.383,
  "baseShare": 0.371,
  "lift": 1.032,
  "lo": 0.961,
  "hi": 1.107,
  "z": 0.91
 },
 "A|* MD-AD pair good": {
  "n": 1300,
  "eventShare": 0.356,
  "baseShare": 0.37,
  "lift": 0.963,
  "lo": 0.902,
  "hi": 1.026,
  "z": -1.16
 },
 "U|* MD-AD pair bad": {
  "n": 226,
  "eventShare": 0.296,
  "baseShare": 0.256,
  "lift": 1.158,
  "lo": 0.963,
  "hi": 1.352,
  "z": 1.58
 },
 "U|* AD 6/8 from MD": {
  "n": 226,
  "eventShare": 0.137,
  "baseShare": 0.131,
  "lift": 1.048,
  "lo": 0.77,
  "hi": 1.321,
  "z": 0.32
 },
 "A|* AD yogakaraka": {
  "n": 1300,
  "eventShare": 0.066,
  "baseShare": 0.06,
  "lift": 1.095,
  "lo": 0.895,
  "hi": 1.304,
  "z": 0.97
 },
 "A|* MD+AD in raja yoga": {
  "n": 1300,
  "eventShare": 0.418,
  "baseShare": 0.4,
  "lift": 1.045,
  "lo": 1.002,
  "hi": 1.088,
  "z": 1.76
 },
 "A|* Sat good from Moon": {
  "n": 1300,
  "eventShare": 0.257,
  "baseShare": 0.247,
  "lift": 1.038,
  "lo": 0.943,
  "hi": 1.137,
  "z": 0.82
 },
 "U|* last AD of MD (chidra)": {
  "n": 226,
  "eventShare": 0.133,
  "baseShare": 0.115,
  "lift": 1.156,
  "lo": 0.812,
  "hi": 1.511,
  "z": 0.91
 }
};

export interface ScoreEvidence { event: 'A' | 'M' | 'U'; want: 'high' | 'low'; n: number; mean: number; lo: number; hi: number }
export const SCORE_EVIDENCE: Record<'career' | 'wealth' | 'relationships' | 'health' | 'general' | 'overall', ScoreEvidence> = {
 "career": {
  "event": "A",
  "want": "high",
  "n": 1300,
  "mean": 0.503,
  "lo": 0.487,
  "hi": 0.519
 },
 "wealth": {
  "event": "A",
  "want": "high",
  "n": 1300,
  "mean": 0.501,
  "lo": 0.486,
  "hi": 0.517
 },
 "relationships": {
  "event": "M",
  "want": "high",
  "n": 391,
  "mean": 0.481,
  "lo": 0.454,
  "hi": 0.508
 },
 "health": {
  "event": "U",
  "want": "low",
  "n": 226,
  "mean": 0.549,
  "lo": 0.51,
  "hi": 0.588
 },
 "general": {
  "event": "A",
  "want": "high",
  "n": 1300,
  "mean": 0.503,
  "lo": 0.487,
  "hi": 0.518
 },
 "overall": {
  "event": "A",
  "want": "high",
  "n": 1300,
  "mean": 0.5,
  "lo": 0.485,
  "hi": 0.515
 }
};
