/**
 * Writes src/lib/core/evidenceTable.ts — the measured track record the app shows
 * beside each classical indicator and each area score.
 *
 *   BT_DATA=people550 TZ=UTC npm run backtest -- backtest/comboEval.ts     (first; writes data/combo_results.json)
 *   BT_DATA=people550 TZ=UTC npm run backtest -- backtest/writeEvidence.ts
 *
 * Indicators: pooled over all 544 lives (the rules were pre-registered and none
 * was tuned, so pooling every split gives the tightest honest estimate), local
 * ±4-year baseline, person-bootstrap 95% interval — straight from comboEval.
 *
 * Area scores: where the engine's own area score sat, on each event date, among
 * the same person's scores within ±4 years (mid-rank percentile, 0.5 = chance),
 * for the event type the area should foreshadow.
 */
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { DashaPredictionEngine } from '../src/lib/core/predictions';
import { INDICATORS } from '../src/lib/core/classicalIndicators';
import { PEOPLE, cast, chainAt, grid, at, percentile, clusterMean, DAY, type Cast, type Chain } from './lib';

const res = JSON.parse(readFileSync(path.resolve(__dirname, 'data/combo_results.json'), 'utf-8'));
const pooled = res.pooled as Record<string, { O: number; E: number; n: number; lift: number; lo: number; hi: number; z: number }>;

const ind: Record<string, object> = {};
for (const d of INDICATORS) {
  const p = pooled[d.evidence];
  if (!p) throw new Error(`no backtest result for ${d.evidence}`);
  ind[d.evidence] = { n: p.n, eventShare: +(p.O / p.n).toFixed(3), baseShare: +(p.E / p.n).toFixed(3), lift: p.lift, lo: p.lo, hi: p.hi, z: p.z };
}

// ── area scores at events, local ±4y percentile ─────────────────────────────
const engine = new DashaPredictionEngine();
const AREAS = ['career', 'wealth', 'relationships', 'health', 'general', 'overall'] as const;
const FOR: Record<(typeof AREAS)[number], { event: 'A' | 'M' | 'U'; want: 'high' | 'low' }> = {
  career: { event: 'A', want: 'high' }, wealth: { event: 'A', want: 'high' }, relationships: { event: 'M', want: 'high' },
  health: { event: 'U', want: 'low' }, general: { event: 'A', want: 'high' }, overall: { event: 'A', want: 'high' },
};
const memo = new Map<string, Record<string, number>>();
function scores(c: Cast, ch: Chain) {
  const k = `${c.person.id}|${ch.md}|${ch.ad}|${ch.pd}`;
  let s = memo.get(k);
  if (!s) {
    const p = engine.generateCompletePrediction(ch.md, ch.ad, ch.pd, undefined, c.ctx, 'en');
    s = Object.fromEntries(AREAS.map(a => [a, a === 'overall' ? p.overallScore : p.predictions[a].score]));
    memo.set(k, s);
  }
  return s;
}
const HALF = 4 * 365.25 * DAY;
const by: Record<string, Map<number, number[]>> = {};
for (const person of PEOPLE) {
  const c = await cast(person);
  const end = person.death ? at(person.death) : new Date('2026-10-08T12:00:00Z');
  const G = grid(c.birth, end, 15).map(d => ({ t: d.getTime(), ch: chainAt(c, d) })).filter(g => g.ch) as { t: number; ch: Chain }[];
  const evs: { type: string; t: number }[] = [];
  for (const e of person.events) if (!e.posthumous && e.date) for (const cat of e.cats) evs.push({ type: cat, t: at(e.date).getTime() });
  for (const area of AREAS) {
    const { event } = FOR[area];
    for (const ev of evs.filter(e => e.type === event)) {
      const win = G.filter(g => Math.abs(g.t - ev.t) <= HALF);
      if (win.length < 24) continue;
      const ch = chainAt(c, new Date(ev.t)); if (!ch) continue;
      const sorted = win.map(g => scores(c, g.ch)[area]).sort((a, b) => a - b);
      const m = (by[area] ??= new Map());
      m.set(person.id, [...(m.get(person.id) ?? []), percentile(sorted, scores(c, ch)[area])]);
    }
  }
}
const score: Record<string, object> = {};
for (const area of AREAS) {
  const r = clusterMean(by[area]);
  score[area] = { event: FOR[area].event, want: FOR[area].want, n: r.n, mean: +r.mean.toFixed(3), lo: +r.lo.toFixed(3), hi: +r.hi.toFixed(3) };
  console.log(area.padEnd(14), JSON.stringify(score[area]));
}

const ev = res.eventCounts as Record<string, number>;
const sumType = (t: string) => Object.entries(ev).filter(([k]) => k.endsWith(`|${t}`)).reduce((s, [, v]) => s + v, 0);
const meta = { people: PEOPLE.length, events: { A: sumType('A'), M: sumType('M'), U: sumType('U') }, generated: new Date().toISOString().slice(0, 10) };

const out = `/**
 * GENERATED by backtest/writeEvidence.ts from the 550-lives backtest — do not edit
 * by hand; rerun the script (see backtest/README.md) when a rule or score changes.
 *
 * INDICATOR_EVIDENCE: for each classical indicator (classicalIndicators.ts), the
 * share of real dated events it was present at versus the share of the same
 * people's nearby days (±4 years) — lift = the ratio, lo/hi its 95% interval,
 * z the standard score of the difference (the app calls a difference "clear"
 * only at |z| >= 3, because ~36 indicators are shown side by side).
 * SCORE_EVIDENCE: where the engine's own area score sat at those events among
 * the person's nearby periods (0.5 = what chance gives).
 */
export const EVIDENCE_META = ${JSON.stringify(meta)} as const;

export interface IndicatorEvidence { n: number; eventShare: number; baseShare: number; lift: number; lo: number; hi: number; z: number }
export const INDICATOR_EVIDENCE: Record<string, IndicatorEvidence> = ${JSON.stringify(ind, null, 1)};

export interface ScoreEvidence { event: 'A' | 'M' | 'U'; want: 'high' | 'low'; n: number; mean: number; lo: number; hi: number }
export const SCORE_EVIDENCE: Record<'career' | 'wealth' | 'relationships' | 'health' | 'general' | 'overall', ScoreEvidence> = ${JSON.stringify(score, null, 1)};
`;
writeFileSync(path.resolve(__dirname, '../src/lib/core/evidenceTable.ts'), out);
console.log('wrote src/lib/core/evidenceTable.ts', JSON.stringify(meta));
