/**
 * Turns backtest/data/calibration.json (output of calibrate.ts) into
 * src/lib/core/calibrationTable.ts. Run after re-running calibrate.ts:
 *   TZ=UTC npx vite-node --config backtest/vite.config.ts backtest/calibrate.ts 600 40 > backtest/data/calibration.json
 *   npx vite-node --config backtest/vite.config.ts backtest/writeCalibration.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const d = JSON.parse(readFileSync(path.resolve(__dirname, 'data/calibration.json'), 'utf-8'));
const rows = Object.entries(d.quantiles as Record<string, number[]>)
  .map(([k, v]) => `  ${k}: [${v.join(', ')}],`).join('\n');
const src = `/**
 * AUTO-GENERATED by backtest/writeCalibration.ts — do not edit by hand.
 *
 * Raw 1–10 score quantiles for each life area and the overall rating, measured
 * over ${d.samples} periods drawn from ${d.charts} random charts (random birth date 1900–2005,
 * place and time; random date within each chart's adult life) through the real
 * current-period pipeline, live gochara included.
 *
 * Entry i is the raw score at percentile PERCENTILES[i].
 */
export const PERCENTILES = [${d.percentiles.join(', ')}] as const;

export const SCORE_QUANTILES: Record<'overall' | 'career' | 'wealth' | 'relationships' | 'health' | 'general', number[]> = {
${rows}
};
`;
writeFileSync(path.resolve(__dirname, '../src/lib/core/calibrationTable.ts'), src);
console.log('wrote calibrationTable.ts');
